### ISSUE TITLE
license confusion - GPL v2 or v3?

### ISSUE THREAD

**Issue by retlehs** [discourse/wp-discourse#100]
the [LICENSE file](https://github.com/discourse/wp-discourse/blob/d13e804e272369ea82c5aa6574cca1907e8bca13/LICENSE) says GPLv3, but the [plugin file](https://github.com/discourse/wp-discourse/blob/d5bf744cc34b7bf20cc98364ee11ae68a9167486/wp-discourse.php#L9-L24) says GPLv2

(fyi, i put GPLv3 in  `composer.json` via #93)

**Comment by eviltrout** [comment]
Generally we license all our repos as MIT except for core discourse.

Is there a reason this is GPL @coding-horror or @SamSaffron?

**Comment by tnorthcutt** [comment]
@eviltrout FWIW, the WordPress stance is that plugins are derivative works, and thus inherit the GPL: https://wordpress.org/about/license/. I'm advocating for or against that stance – just pointing out some information :smile:
