### ISSUE TITLE
Participate name error

### ISSUE THREAD

**Issue by swalkinshaw** [discourse/wp-discourse#109]
In the custom HTML this plugin has a `{fullname}` variable which references `$participant->name`. See https://github.com/discourse/wp-discourse/blob/dd417edad986da16420826800ffe4d28812c53df/templates/comments.php#L60

Problem is that Discourse itself doesn't include the `name` attribute. See these serializers:

https://github.com/discourse/discourse/blob/f66c39c63bfa57318f742b672b02a02ab18b68a3/app/serializers/basic_user_serializer.rb
https://github.com/discourse/discourse/blob/f66c39c63bfa57318f742b672b02a02ab18b68a3/app/serializers/user_wordpress_serializer.rb

So either this option should be removed in this plugin, or `name` should be added over on Discourse.

**Comment by retlehs** [comment]
closed by #187
