### ISSUE TITLE
Does Composer work?

### ISSUE THREAD

**Issue by arlair** [discourse/wp-discourse#111]
Hi, my first time using Composer, but I got the all other WordPress plugins I use to install okay, eg

"wpackagist-plugin/wordpress-seo": "~1.7",

With wp-discourse I get:

The requested package discourse/wp-discourse could not be found in any version.

It sounds like it does not find it at all. I tried:
 "discourse/wp-discourse": "*",

and also "~0.6", "dev-master".

Any help appreciated.

**Comment by retlehs** [comment]
it doesn't since this repo has no tagged releases. see #96 / https://github.com/discourse/wp-discourse/issues/96#issuecomment-68752066

**Comment by arlair** [comment]
Ahh, okay, thanks :). The readme on the front page suggests it would work, so I guess it got ahead of itself ;)

**Comment by retlehs** [comment]
working now!
