### ISSUE TITLE
sync.php?

### ISSUE THREAD

**Issue by retlehs** [discourse/wp-discourse#112]
what is this file? it's not used by the plugin or referenced anywhere in the repo

is it documented somewhere else? if so, let's get that added to the README

**Comment by arlair** [comment]
I assume it is mean to be called via a cronjob to sync any updates made on your WordPress article to the excerpt on the related Discourse page.

It seems it will only do this for the last 3 modified pages though. I guess if there are more than 3 updates the extra ones will not be synced.
