### ISSUE TITLE
synced discourse comments with assets cause 404s

### ISSUE THREAD

**Issue by retlehs** [discourse/wp-discourse#113]
if a comment on discourse includes an asset (e.g. an image), the asset source needs the discourse URL prepended to avoid 404s.

![image](https://cloud.githubusercontent.com/assets/115911/5989679/f17c16d8-a954-11e4-93e3-4bfc5bb9e9d3.png)

ref https://meta.discourse.org/t/emojis-not-displaying-old-avatar-styles/13986

**Comment by pjv** [comment]
Except don't make already absolute URLs *absoluter*. See #131.
