### ISSUE TITLE
SSO Not Working In Some Scenarios

### ISSUE THREAD

**Issue by arlair** [discourse/wp-discourse#115]
I was moving my WordPress install to a VPS which is using nginx. Discourse SSO did not work with this plugin.

I switched the Discourse server to point to a dev environment running Apache and it worked using exactly the same settings (they were autocompleted by the browser when configuring it).

I then tried the SSO plugin found here:
https://github.com/PrimeTimeCode/pt-wp-discourse-sso

That plugin works fine on the VPS running nginx.

I tried to disable any possible plugins, but the wp-discourse plugin's SSO would still not work. It seemed like the hook was not getting called by the plugin to process the SSO after being redirected to the WordPress login page. The other plugin has slightly different code to do this, so I have switched to using it for now.

I was trying to set up a Ubuntu dev environment with nginx, but a combination of constantly changing IP addresses, single user third party internet and Hyper-V have made it more trouble than it is worth until I move locations soon. My PHP skills are pretty lacking too, so I'm not sure what the exact cause is.

**Comment by pjv** [comment]
Just adding another datapoint here. I have the same issue. I also run on nginx. I am successfully using the PrimeTime SSO plugin, but the SSO functionality of the wp-discourse plugin is not working for me.

**Comment by solhuebner** [comment]
Nginx is really good for heavy load sites. Can someone please try to fix this? Kind regards

**Comment by henrynet** [comment]
Would you please to check/edit the nginx conf for testing the rewire rules?

ref: https://wordpress.org/support/topic/cant-access-custom-query-vars-permalinks-nginx

SSO of my Wordpress site works fine with the follows nginx conf:

        location / {
                try_files $uri $uri/ /index.php?q=$uri&$args;
        }

**Comment by pjv** [comment]
@henrynet I tried that nginx conf modification and it made no difference in my case - the SSO from the wp-discourse plugin still does not work; after an attempted login from the Discourse forum, I am logged in on wordpress and then redirected to my wordpress account management page and am never logged in to Discourse. PrimeTime SSO still works perfectly.

I've looked at the SSO code for each plugin perfunctorily and they are not hugely different, being both based on the same original codebase. I didn't have time to dig hard enough to figure out what the crucial difference is. It would be nice to run just one plugin instead of two, but since PrimeTime is working and I have other stuff to pay attention to...

**Comment by etcook** [comment]
It looks like the primary difference between our handling is this plugin uses $wp->query_vars, and I use $_GET directly.

@pjv are you adept enough at PHP to change that mechanism, and see if calling $_GET directly works?

On the surface, I don't see why this plugin would be failing.

**Comment by pjv** [comment]
hey, thanks @etcook, i'll take a look at both plugins again with that in mind and see if i can figure it out how to replace the $wp->query_vars call with $_GET. if i get it working, i'll put up a PR for wp-discourse.

**Comment by pjv** [comment]
It actually ended up not having anything to do with the query vars, but instead it seems that wp-discourse was not getting the current logged in user information correctly once the login was done. weird, but just substituting the same `wp_get_current_user()` call being used in @etcook's PrimeTime plugin fixed this issue for me. See the PR #132

**Comment by pjv** [comment]
@etcook it doesn't seem to me to be the query_vars / $_GET issue. i replaced everything and it still doesn't work at all. 

after messing around with this for a few hours, i finally have come to the conclusion that the OP is exactly right and the action for processing the SSO call on the wordpress side (`sso_parse_request`) is either not being registered correctly or it is not being called for whatever reason when the request comes in for the WP login page. after all my testing, i am pretty sure that function is never being called in my environment.

i'm afraid that debugging that deep is more time than i can put in, given that the corresponding callback in @etcook's PrimeTime SSO plugin (`interceptSSORequest`) is being called and that plugin works perfectly in my environment.

**Comment by pjv** [comment]
i think i finally found the issue and the simple patch in PR #156 fixes this for me on my system.

**Comment by etcook** [comment]
@pjv kudos on this.
