### ISSUE TITLE
downstream improvements

### ISSUE THREAD

**Issue by retlehs** [discourse/wp-discourse#116]
see https://github.com/10up/wp-discourse

would like to get these improvements in this repo as well.. @aliso, any reason why y'all haven't submitted PR's upstream?

**Comment by retlehs** [comment]
:+1:

https://github.com/10up/wp-discourse/commit/5c9d43c4333e136204d5a3b07192f4b368c3f518
https://github.com/10up/wp-discourse/commit/ed9b1ec0ba9aff86aab6b8b266446f2055b9c3e0
https://github.com/10up/wp-discourse/commit/da52403644016709574338ca6723526734061327

**Comment by tnorthcutt** [comment]
FWIW you probably wouldn't want to incorporate https://github.com/10up/wp-discourse/commit/ed9b1ec0ba9aff86aab6b8b266446f2055b9c3e0 since it makes use of a VIP-specific function. But otherwise, 👍
