### ISSUE TITLE
Sub-categories ignored

### ISSUE THREAD

**Issue by KGNF** [discourse/wp-discourse#126]
When I go to the "Published category" dropbox, I cannot see any sub-categories listed here.
In the previous version, adding the name of the sub-category worked just fine.

Any idea for a workaround?

**Comment by KGNF** [comment]
Still an issue, but I did find a workaround.

Basically, move desired category to root, this will make it available in the drop down, and after being saved you can move it back and wp-discourse will keep posting to it.

**Comment by scossar** [comment]
This has been added to the latest version.
