### ISSUE TITLE
How to install without using Composer?

### ISSUE THREAD

**Issue by jay129** [discourse/wp-discourse#128]
the installation section only mentioned using Composer.
asked a few contributors neither do they have heard of composer.
am i missing something? if someone can point me to the right direction that'll be greatly helpful.
thanks.

**Comment by retlehs** [comment]
see https://meta.discourse.org/t/can-i-install-wp-discourse-without-composer/25784

**Comment by jay129** [comment]
Thank you SOOO much Ben!
tried to ask you directly but didn’t figure how so i posted the question.
i searched all over discourse meta weeks ago but couldn’t find the link you provided…..which is odd.
anyway thank you for the help again!
