### ISSUE TITLE
Publish to Discourse option now missing

### ISSUE THREAD

**Issue by pixeldynamo** [discourse/wp-discourse#129]
Just upgraded to 0.6.5 and the 'Publish to Discourse' checkbox is now missing from the post interface.

Publishing posts doesn't default to Discourse publishing either, the custom field is created, but remains set to 0. If I manually update the value to 1 and update the post the Discourse posts is created.

Auto Publish in settings is enabled.

**Comment by retlehs** [comment]
unable to reproduce on the latest wordpress, latest version of the plugin on a fresh install

![image](https://cloud.githubusercontent.com/assets/115911/6703144/dbcc8024-cd04-11e4-88f0-5ecc2f519fa2.png)

**Comment by FromStoneage** [comment]
Hi, I'm experiencing the same problem with the latest _WordPress_ and _wp-discourse_ any idea how you resolved the issue ?

**Comment by scossar** [comment]
On the wp-discourse settings page do you have the post-type you are trying to publish selected?

![screenshot 2016-07-06 13 46 50](https://cloud.githubusercontent.com/assets/2975917/16633903/3ca13dfc-4380-11e6-8466-24abfc2b644b.png)

**Comment by FromStoneage** [comment]
@scossar omg thank you so much ! this solves it, this is a poor UI config setting ...

**Comment by scossar** [comment]
Great! There is a new version of the plugin coming out right away that
makes a few improvements to the UI.
