### ISSUE TITLE
HTML embed blocks - where?

### ISSUE THREAD

**Issue by RickCogley** [discourse/wp-discourse#130]
Hi - the plugin is working for me, and I can get my WP to add an entry in my discourse as expected. 

There are two HTML blocks, one for if there are no comments, one for if there are some already, which I want to ask about. When I paste this into the body of the blog post, the codes in the curly brackets are not being converted to their values. You just see the codes themselves in the post. 

Is this the expected behavior? Do I need to do something special in the post to get these to show, or, do I need to add these to my template to get them to work? 

Please advise. Thanks in advance!

**Comment by RickCogley** [comment]
Sorry, I thought I had to turn off commenting and let the Discourse system take over for that. 

Now that I turned it on, the blocks are showing up. 

(No comments are getting sync'ed back, though, from the Discourse forum)

**Comment by retlehs** [comment]
> (No comments are getting sync'ed back, though, from the Discourse forum)

double check your settings.

**Comment by RickCogley** [comment]
Thanks @retlehs. Somehow it is working now!
