### ISSUE TITLE
problems with publishing to discourse (urgent)

### ISSUE THREAD

**Issue by gingerling** [discourse/wp-discourse#138]
Hi, we just launched phpList.org with discuss.phpList.org on discourse. We tested before launch and had no problems.

We have two post types, post (normal) and newslists (custom, for phpList staff only). I selected both post types from the list in the plugin settings (using ctrl click to omit others). First news we published was from newslist, that got it's linked thread fine. Second was a normal blog: it got a link but no thread, when I click the link I get  "Account login timed out, please try logging in again"

Tried a few things. Tried un-publishing and re-publishing the post, also went into settings and just chose posts (so removes newslists for now) and then re-published, but no change.

Anyone know what to do?

**Comment by gingerling** [comment]
ah, ok solved it 

it was wrong username in Publishing username - cause we have buddypress there is some confusion about names... 

So, a feature request: names suggestions in publishing username. Also, flexibility here would be nice, it would be good to change the name based on post.

**Comment by pixeldynamo** [comment]
You can specify a global username and a username on each WordPress account. The plugin will use the account associated with the author before falling back to the global username. Is there a third case?

**Comment by gingerling** [comment]
So far, every situation uses the "publishing username" as defined in the discourse settings accessed by admins.

This feature of "user name on each wordpress account" and "use the account associated with the author" I have trouble with. In the settings it says "Discourse username of publisher (will be overriden if Discourse Username is specified on user)"

I have tried numerous tests but each one simply uses the name set as publishing username.
Is there some setting to make this "specified on user" work? Also, which situations trigger fallback mechanism?

Thanks for your help: our forums are going well so far :)

**Comment by pixeldynamo** [comment]
The username on the WordPress account is a field called 'Discourse Username' added to the user, editable by an administrator or the user themselves. If the Discourse username is specified there, then it should post on behalf of the named user.

**Comment by gingerling** [comment]
ah yes, so I see that in the profile editor. So I tested now and the outcome was the the discourse entry was correct "ethical pets", but the entry in wordpress still said "gingerling"  - though I think that is some wordpress problem.

So, I guess the question is that with in the scope of this plugin as SSO, what is the discourse username? Isn't that the same as the WP username? So why is the box needed?

**Comment by pixeldynamo** [comment]
AFAIK SSO doesn't use the username, it matches the email address.

**Comment by gingerling** [comment]
but you create your account in WP so theoretically, unless you ran both sites before SSO and then added SSO, they are the same?

**Comment by pixeldynamo** [comment]
Sure but it has to match on the email because in cases where SSO is established later it can't assume that the same username at both ends is the same user. The email is the identity object (as much as it shouldn't be).
