### ISSUE TITLE
How to track new releases?

### ISSUE THREAD

**Issue by rata** [discourse/wp-discourse#139]
Hi,

I want to be notified about new plugin releases so I can update easily. But as the plugin is not included in wordpress.org yet, I don't know to do it.

I checked https://meta.discourse.org/c/releases but it seems only to discourse it self.

Do you have any mailing list or plan to include it in wp.org soon ?

Thanks a lot,
Rodrigo

**Comment by retlehs** [comment]
https://github.com/afragen/github-updater

https://github.com/discourse/wp-discourse/releases

https://packagist.org/packages/discourse/wp-discourse

**Comment by rata** [comment]
Thanks!

Now that you point out this, I find out I can subscribe to an atom feed. Like:
https://github.com/discourse/discourse/releases.atom
https://github.com/discourse/wp-discourse/releases.atom

So, that's easier for me. Thanks a lot!
