### ISSUE TITLE
Comment counts not synced

### ISSUE THREAD

**Issue by pixeldynamo** [discourse/wp-discourse#140]
Comments on articles are visible, but the counts are not.

Can you confirm what the WordPress theme needs to utilise to display Discourse comment counts?

**Comment by pixeldynamo** [comment]
Could really do with some assistance on this one, even if it's just to point me in the right direction for our other developer to resolve.

**Comment by pixeldynamo** [comment]
Ok, I've got a solution for this. As it's a standard wp function would you like a push request with the fix?

**Comment by retlehs** [comment]
sure

**Comment by jplacht** [comment]
@pixeldynamo What solution did you find?

I experimented a lot today, but only comments_popup_link() seems able to get the correct number of comments including the ones from Discourse. Can you help set up a new function or adopt get_comments_number() to include both WP + Discourse replies?

**Comment by Draco351** [comment]
What hapenned with this? @pixeldynamo @retlehs is there any fix?

**Comment by pixeldynamo** [comment]
Our fix was only partial and wasn't pushed because it masks the root cause. 

This probably needs to be properly investigated by @retlehs.

**Comment by scossar** [comment]
I think we can add a template for displaying the comment count. Something like this might work:

![screenshot 2016-05-27 18 08 25](https://cloud.githubusercontent.com/assets/2975917/15624196/356b9a5a-2436-11e6-9887-0c5f670dffa7.png)

The idea is to give some sort of indication if there are more replies on the forum than are being displayed on the WordPress site.

The numbers are available in `comments.php` as

```php
$total_comments = get_post_meta( $post->ID, 'discourse_comments_count', true );
$displayed_comments = count( $discourse_info->posts );
```

**Comment by scossar** [comment]
The next update of the plugin adds an option to create a Join Discussion link that displays the Comments Count.
