### ISSUE TITLE
Old WP posts being republished to Discourse

### ISSUE THREAD

**Issue by tcn33** [discourse/wp-discourse#145]
After the latest update I am seeing old WP posts (ranging from 2 to 8 months old) being pushed to Discourse. It happens intermittently, three times in the past week, and the posts in question have not been edited recently.

**Comment by retlehs** [comment]
what other plugins are you using?

**Comment by tcn33** [comment]
These are all of the other active ones.

![screen shot 2015-05-14 at 7 36 51 am](https://cloud.githubusercontent.com/assets/7378906/7621698/1d2e633c-fa0c-11e4-8634-614ad1b00fdd.png)

**Comment by Draco351** [comment]
That is happening to us. When someone visits for the first time a post, since you added Discourse as comment system in WP, it will create a new topic on the forum. 

Is not random, it's just trying to load a comments from a topic that doesn't exist, and that creates a new one.

**Comment by scossar** [comment]
There was an issue that any WordPress posts that were edited through XMLRPC were being published to Discourse. This is now fixed. Hopefully that was what was causing your problem.
