### ISSUE TITLE
"Leave a reply" in WP still visible and does not link to discourse

### ISSUE THREAD

**Issue by gingerling** [discourse/wp-discourse#149]
Hi, in our blogs eg: https://www.phplist.org/beta-testers-needed-for-new-plugin we still have "leave a reply" at the top, it links to https://www.phplist.org/beta-testers-needed-for-new-plugin/#respond and does not seem to interact with the discourse plugin at all, eg, does not take us to the bottom with the discourse link, or directly to discourse

**Comment by retlehs** [comment]
probably not a bug with the plugin. can you please open a support thread on meta.discourse.org?

**Comment by gingerling** [comment]
ok. Does the wp link "leave a reply" show up on yours?
