### ISSUE TITLE
Updating wp post should update discourse one?

### ISSUE THREAD

**Issue by bsides** [discourse/wp-discourse#151]
I would like to know if I'm having some kind of error or it's just not happening. When I update a post in wordpress the same in Discourse isn't updated. I know the API can do it but it doesn't seem to happen. If it's working as intended then I'm sorry.

Thanks again!

**Comment by tnorthcutt** [comment]
It's not just you, this looks to be disabled on purpose:

https://github.com/discourse/wp-discourse/blob/9bfd4d6dac64bebd6704cf67d6d25f732d189119/lib/discourse.php#L510

**Comment by tnorthcutt** [comment]
After much digging, I found the commit that changed this: https://github.com/discourse/wp-discourse/commit/9d5975d4775cb36c16f1e0fd080c5734e2bc7f44

@SamSaffron do you happen to remember what the problem with allowing updates was?

**Comment by tnorthcutt** [comment]
After doing some more testing, I've got this _sort of_ working, but I'm starting to see how complicated it is and how many edge cases there could be. Regardless, I may put together a PR with this for public comment.
