### ISSUE TITLE
No comments displayed 

### ISSUE THREAD

**Issue by smth** [discourse/wp-discourse#154]
I'm not seeing any comments, the "use when there are no replies" template is always used.

**Comment by nebri-scripts** [comment]
I am also not seeing any comments. Are we doing something wrong? Posting from wordpress to discourse works just fine though.

**Comment by neonacorns** [comment]
What worked for me was explicitly checking the "Publish to Discourse" option in the **Publish** block in my WP post editing view, then updating.

Previously, I could successfully publish TO Discourse, but Discourse-based comments were not appearing in the post itself, even with all the plugin settings at their most liberal.

**Comment by Lonaris** [comment]
Okay, it took a lot of time for me to make it work and display the comments. It just didn't pull them at all from the Discourse until I got these settings right:
- Publishing username had to be "system". (This one is important, even if it doesn't look like that)
- A minimun trustlevel and all of those settings regarding security.
- Checking the "Publish to Discourse" option in the Publish block of the Wordpress post editing view.

Still, while comments are being pulled right now, the date/time shows "January 1st, 1970". Which is cool, but not accurate.
Note: If you have the wp account and the discourse account sync'd then you will get a pretty weird glitch, the user who posts on Discourse will be both "system" and the user from wp.
