### ISSUE TITLE
Posts to Discourse with generated excerpt

### ISSUE THREAD

**Issue by jhamilton09** [discourse/wp-discourse#166]
With the plugin configured to post an excerpt, it posts the automatically generated excerpt (first 250 characters) I instead of the custom made excerpt from the article. It should use the custom excerpt if one exists or have the option to choose in the plugin's settings.

**Comment by tnorthcutt** [comment]
This would be pretty easy to add. @retlehs – would a PR for this be welcomed?

**Comment by scossar** [comment]
See https://github.com/discourse/wp-discourse/pull/210

**Comment by scossar** [comment]
This feature has been added to the latest version of the plugin.
