### ISSUE TITLE
Feature request - trust level in wordpress profile

### ISSUE THREAD

**Issue by drreen** [discourse/wp-discourse#167]
Hey guys

I am looking for a way to set user's trust level to tl2 after a woocommerce purchase. Would it work through a custom user profile field?

**Comment by tnorthcutt** [comment]
You'd need to hook into a WooCommerce action to do that. I think the Discourse API would allow setting the trust level, by issuing a PUT to `http://yourdomain.com/admin/users/{user_id}/trust_level`.

I suggest looking at how the plugin currently interacts with the API, e.g. [here](https://github.com/discourse/wp-discourse/blob/master/lib/discourse-publish.php#L222).
