### ISSUE TITLE
Box comment on Wordpress articles

### ISSUE THREAD

**Issue by Draco351** [discourse/wp-discourse#169]
Should be nice using the Discourse login at Wordpress to allow readers posting comments from the article itself, also interacting with other ones. Something like this (is not WP, but you can see on left a box comment to post simple comments):

![Imagen de Vandal foros](http://i.imgur.com/dtbmhAW.jpg)

**Comment by ZogStriP** [comment]
Please use https://meta.discouse.org for issues with this plugin.
