### ISSUE TITLE
Indentation of comments

### ISSUE THREAD

**Issue by Draco351** [discourse/wp-discourse#170]
Using Discourse at Wordpress as comments system, our replies shows like this, as you can see [also at our webpage](http://winphonemetro.com/2015/11/build-10586-windows-10-anillo-lento):

![Discourse comments](https://meta-s3-cdn.global.ssl.fastly.net/original/3X/c/a/ca0326450a748a1769d0d44a2deb740f1f6ce190.jpg)

But would be nice if we could show comments in this way:

![Indentation](https://meta-s3-cdn.global.ssl.fastly.net/original/3X/6/5/65a9abca6037b914e9d27d831131f744d7d8bb13.png)

**Comment by ZogStriP** [comment]
Please use https://meta.discourse.org for issues with plugins.
