### ISSUE TITLE
Cannot Post to Discourse instance, Published Category does not Display in settings

### ISSUE THREAD

**Issue by jdtoppin** [discourse/wp-discourse#174]
Receiving a number of different errors as per the logs depending on which page I'm on as per the following:

Posting a post:

>2016/01/18 12:52:51 [error] 4319#0: *3320 FastCGI sent in stderr: "PHP message: PHP Warning: First parameter must either be an object or the name of an existing class in /var/www/josiahtoppin.com/htdocs/wp-content/plugins/wp-discourse-0.6.6/lib/discourse.php on line 507" while reading response header from upstream, client: 142.229.86.182, server: josiahtoppin.com, request: "POST /wp-admin/post.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "www.josiahtoppin.com", referrer: "http://www.josiahtoppin.com/wp-admin/post.php?post=8587&action=edit"

Loading the plugin page:

>2016/01/18 12:59:35 [error] 4319#0: *3420 FastCGI sent in stderr: "PHP message: PHP Warning: Invalid argument supplied for foreach() in /var/www/josiahtoppin.com/htdocs/wp-content/plugins/wp-discourse-0.6.6/lib/admin.php on line 257" while reading response header from upstream, client: 142.229.86.182, server: josiahtoppin.com, request: "GET /wp-admin/options-general.php?page=discourse HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "www.josiahtoppin.com", referrer: "http://www.josiahtoppin.com/wp-admin/options-general.php?page=discourse"

And loading a post page:

>2016/01/18 12:54:15 [error] 4319#0: *3363 FastCGI sent in stderr: "PHP message: PHP Warning: First parameter must either be an object or the name of an existing class in /var/www/josiahtoppin.com/htdocs/wp-content/plugins/wp-discourse-0.6.6/lib/discourse.php on line 507

>PHP message: A valid URL was not provided" while reading response header from upstream, client: 142.229.86.182, server: josiahtoppin.com, request: "GET /2016/01/we-shall-get-this-working/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "www.josiahtoppin.com", referrer: "http://www.josiahtoppin.com/blog/"

I've triple checked config, regenerated API, yet the issue persists. Seen a few topics on meta in regards to the issue, but never any replies or solutions. Both discourse/wordpress run on same server on different ports if it makes any difference. I'm not an expert by any means.

I can never select a published category nor does the comment link over to the discourse instance.

App and nginx config as follows with real url (example.com) setup:

```
## which TCP/IP ports should this container expose?
expose:
  - "81:80"   # fwd host port 80   to container port 80 (http)
  - "2222:22" # fwd host port 2222 to container port 22 (ssh)
```

```
server {
    listen 80;
    server_name example.com;

location / {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_set_header X-NginX-Proxy true;

    proxy_pass http://127.0.0.1:81/;
    proxy_redirect off;

    # Socket.IO Support
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}
}
```

**Comment by scossar** [comment]
The errors you were getting have hopefully been dealt with through recent updates to the plugin. If you are still having issues with the plugin could you open a new issue on here?
