### ISSUE TITLE
Possible to throttle calls?

### ISSUE THREAD

**Issue by pixeldynamo** [discourse/wp-discourse#178]
Whilst digging through our stats on New Relic I've noticed that Discourse is by far the most time consuming, making up to 2000 calls per minute.

Is this necessary? Is there any way to throttle this behaviour?

<img width="720" alt="screenshot 2016-01-31 20 18 30" src="https://cloud.githubusercontent.com/assets/10160987/12704684/ea0df8a8-c857-11e5-9606-434134093027.png">
<img width="725" alt="screenshot 2016-01-31 20 18 23" src="https://cloud.githubusercontent.com/assets/10160987/12704683/ea0b59d6-c857-11e5-9258-a4f71f3773c7.png">
<img width="758" alt="screenshot 2016-01-31 20 09 39" src="https://cloud.githubusercontent.com/assets/10160987/12704682/ea07309a-c857-11e5-86a5-bee5d6561a41.png">

**Comment by scossar** [comment]
Is this still a problem?

The plugin hooks into the WordPress `comments_number` filter so that it returns the count of Discourse comments instead of returning the count of WordPress comments. This could result in many calls to the database being made through the plugin. If I'm understanding things correctly, these are calls that would otherwise have been made through WordPress.

**Comment by scossar** [comment]
I spent some time looking at this. The problem I'm seeing is that unless the plugin has a cached version of a post's comments, it has been going through the process of syncing a post's comments with Discourse for each post on an index page. It's doing this to get the current comment number from Discourse, but it creates a huge number of database queries and http requests. I think we can change it to only sync the comments on when a single post or page is being displayed.

**Comment by pixeldynamo** [comment]
Any improvement would be appreciated, it's still the number one resource drain amongst our plugins.

I've not been able to try newer versions of wp-discourse as the last time I did we found the publish format and HTML templates specified were no longer being used, so rolled back to 0.66. If that has been fixed we can give it another go.

**Comment by scossar** [comment]
This should make a big difference. On a category index page displaying 10 posts, where none of the posts have been synced with Discourse in the past 10 minutes and all the posts have at some time been published to Discourse, making this change results in approximately 50 fewer database queries and goes from making 10 HTTP requests to 0. The downside is that the comment numbers for the posts might not be up to date. We can look at finding a more efficient way of getting the current comments numbers.

Another way to reduce HTTP request to Discourse from the plugin would be to remove the user's avatars from your comments template.

The HTML templates are not going to be added back to the options page. In the latest version - 1.0.0, out sometime tomorrow - the user facing text in the templates can be set on the options page. The HTML templates can be customized very easily in your theme's `functions.php` file. There's a page on the plugin's wiki about it. If you have any problems with that, let me know.

**Comment by scossar** [comment]
This has been improved quite a lot over the past few releases. There are still a few places the code can be improved.
