### ISSUE TITLE
Transient for publish category gets set on failure.

### ISSUE THREAD

**Issue by eaceaser** [discourse/wp-discourse#179]
I had a mismatch with some settings and that caused a permission denied response. 

The plugin never actually checks the response for the categories.json api call, and caches the failed lookup. This causes the categories list to not populate for another hour.

The category lookup failure should be tested, and, additionally, the transient should be invalidated on settings update.

**Comment by scossar** [comment]
This has been fixed here:
https://github.com/discourse/wp-discourse/commit/0d200d9cceac2e960508dbf333862b1cd7f96d0b
