### ISSUE TITLE
Fatal error on activation (Wordpress 4.5.1)

### ISSUE THREAD

**Issue by serfma** [discourse/wp-discourse#183]
I'm getting a fatal error attempting to activate the plugin. I'm on Wordpress 4.5.1.

> Notice: Use of undefined constant __DIR__ - assumed '__DIR__' in /home/curium/public_html/wp-content/plugins/wp-discourse-0.6.6/wp-discourse.php on line 30
> 
> Warning: require_once(__DIR__/lib/discourse.php) [function.require-once]: failed to open stream: No such file or directory in /home/curium/public_html/wp-content/plugins/wp-discourse-0.6.6/wp-discourse.php on line 30
> 
> Fatal error: require_once() [function.require]: Failed opening required '__DIR__/lib/discourse.php' (include_path='.:/usr/share/pear:/usr/share/php') in /home/curium/public_html/wp-content/plugins/wp-discourse-0.6.6/wp-discourse.php on line 30

**Comment by rohmann** [comment]
What version of PHP are you running? `__DIR__` was introduced in 5.3. Ideally you should be on a [supported version](http://php.net/supported-versions.php).

**Comment by serfma** [comment]
PHP version is 5.4.16

**Comment by rohmann** [comment]
It should work on 5.4. Actually, what I find strange is that the error message references `DIR` instead of `__DIR__`. Could you check the contents of that file to confirm?

**Comment by serfma** [comment]
Line 30 of wp-discourse.php indeed is `require_once( __DIR__ . '/lib/discourse.php' );`

**Comment by retlehs** [comment]
`__DIR__` was added in PHP 5.3.0. seems like you're actually running 5.2

**Comment by serfma** [comment]
Yeah my bad, I'm actually on 5.2. Host provider told otherwise.
