### ISSUE TITLE
Move HTML templates from options to functions

### ISSUE THREAD

**Issue by scossar** [discourse/wp-discourse#190]
@retlehs @techAPJ 
Should the html templates be moved from options into functions as has been done here?

https://github.com/10up/wp-discourse/commit/5c9d43c4333e136204d5a3b07192f4b368c3f518

The issue I see this solving is that there is currently no mechanism to restore the templates to their default value if they are accidentally altered. The only drawback that I can see is that the templates would no longer be editable through the plugin's settings page. We could provide some documentation on how to edit the templates through the theme.

**Comment by retlehs** [comment]
closed by #194
