### ISSUE TITLE
Feature Request - Ability to post wordpress post in sub categories.

### ISSUE THREAD

**Issue by ashishdungdung** [discourse/wp-discourse#208]
As mentioned in the title, wish to see the ability to post content to any sub category from wordpress itself. 

Currently we are able to post content to main categories, but i usually post to sub categories instead of the main category and its tiresome to always change the category of post in articles to a sub category after sharing it to discourse.

**Comment by scossar** [comment]
This is an easy change to make. The only problem I can see with doing it is that for some forums it will create a huge list of categories to scroll through.

**Comment by scossar** [comment]
Here's a PR for this: https://github.com/discourse/wp-discourse/pull/212

**Comment by scossar** [comment]
This feature is implemented in the latest version.
