### ISSUE TITLE
Submissions get silently rejected if fails discourse validation

### ISSUE THREAD

**Issue by surrealroad** [discourse/wp-discourse#22]
I tried to publish an article entitled "Scrolls" to discourse, which failed:

```result:{"errors":["Title is too short (minimum is 10 characters)","Title is invalid; try to be a little more descriptive"]}```

I can understand why this is happening, but I think this might happen quite a lot. In my case, I'd like to be able to override Discourse's settings for this, or at least have a way of posting this which makes sense.

**Comment by retlehs** [comment]
yes, there's no proper error reporting

ref #85 
ref #83

**Comment by retlehs** [comment]
closing in favor of #85
