### ISSUE TITLE
Point all post to the same topic at Discourse

### ISSUE THREAD

**Issue by leandropc** [discourse/wp-discourse#235]
Hi, I pretend to use Discourse to replace Wordpress comments function but in a very specific way. The link with the text "START THE DISCUSSION AT...", present in each post when the plugin is activated must point to the same topic.

I have no skill in programming and I was wondering if you can point me to the right direction to make that happen. Thanks in advance.

**Comment by scossar** [comment]
It could be done, but it doesn't sound like a feature that most people would be looking for, so you'd have to create a custom version of the plugin to do it.

You can also ask questions about Discourse/WordPress here: https://meta.discourse.org/c/support/wordpress
