### ISSUE TITLE
update from 0.6.6 to 0.7.0 failed

### ISSUE THREAD

**Issue by adrelanos** [discourse/wp-discourse#236]
```
Updating Plugin WP-Discourse (2/3)

Downloading update from https://downloads.wordpress.org/plugin/wp-discourse.zip…
Unpacking the update…
Installing the latest version…
Removing the old version of the plugin…
Plugin update failed.

An error occurred while updating WP-Discourse: The update cannot be installed because we will be unable to copy some files. This is usually due to inconsistent file permissions. .gitignore, composer.json, lib, templates, .git, uninstall.php, LICENSE, README.md, CHANGELOG.md, sync.php, wp-discourse.php, lib/sso.php, lib/discourse.php, lib/admin.php, templates/comments.php
```

Any idea how to fix that?

**Comment by scossar** [comment]
A quick solution would be to delete the old version and then reinstall the new version. I'll look at this some more later today.

**Comment by scossar** [comment]
If you are updating from 0.6.6 to 0.7.0 keep in mind that The templates are no longer handled from the plugin admin, they must be customized with filters. See this topic for more information about it: https://meta.discourse.org/t/discourse-wordpress-plugin-version-0-7-0/44461

**Comment by adrelanos** [comment]
Simon Cossar:
> If you are updating from 0.6.6 to 0.7.0 keep in mind that The templates are no longer handled from the plugin admin, they must be customized with filters. See this topic for more information about it: https://meta.discourse.org/t/discourse-wordpress-plugin-version-0-7-0/44461

Thank you, I was looking for the changelog anyhow!

**Comment by adrelanos** [comment]
Simon Cossar:
> A quick solution would be to delete the old version and then reinstall the new version.

That worked for me.
