### ISSUE TITLE
Feature Request - SSO fills in discourse_username

### ISSUE THREAD

**Issue by oburt** [discourse/wp-discourse#237]
It would be very useful if after a user auth'ed via SSO that their discourse_username field in WordPress got automatically populated. Currently requires a lot of manual labor to update this field on all of our authors (making the "Publishing username" override of individual user less useful).

I realize this may be difficult due to username on Discourse being editable and therefore resulting in sync issues, but figured it would be worthwhile to at least suggest.

**Comment by scossar** [comment]
This is a fairly easy change to make. It can be done by hooking into the 'wp_login' action - it's triggered after the user logs in -  and making an api call to `"/users/by-external/$user_id.json"` on the Discourse forum. This would also make it possible to add other user attributes from the Discourse forum to the user_metadata table on WordPress - Discourse `groups` and `badges` could possibly be useful.

**Comment by tnorthcutt** [comment]
I may be starting a project soon that would make use of this; if so I can probably develop and submit a PR for it.

@scossar in `/users/by-external/$user_id.json`, is `$user_id` the user's ID on the WP site?

**Comment by scossar** [comment]
I'm working on the plugin right now, so I can make the change to add this in the next couple of days. There's a function that's being used now to get the Discourse user_id on logout. I'd like to move it to the login action and get the Discourse user_id and username there.

**Comment by tnorthcutt** [comment]
Beautiful 👍 

Agreed that badges and groups would be useful for some sites as well

**Comment by drreen** [comment]
@scossar 

Would this solve my current problem?
I want to set trust level = 2 for every woocommerce purchase of a registered user with zapier script. The issue is, that the user might have not created his discourse account yet by going to the forum and trigger the initial SSO registration.

**Comment by scossar** [comment]
No, this won't solve that problem. I'm working on something for adding WordPress users to Discourse groups through SSO that will do most of what you're looking for.

**Comment by drreen** [comment]
@scossar sounds awesome!

Looking forward to test it :)

**Comment by scossar** [comment]
Sorry this has taken so long to get to. The easiest solution that I've found is to use a Discourse webhook. There's a fairly simple implementation of it here: https://github.com/scossar/wp-discourse-wishlist-member/blob/master-webhook/lib/discourse-user.php

The biggest problem with this method is that the WordPress user's `external_id` isn't returned with the information send from Discourse when a user edits their profile. When a user is first created on Discourse through SSO, it's possible to match the Discourse user to a WordPress user by comparing the values for the email address and username. Once a user exists on Discourse, they are able to edit those values, so it's possible that updates to their user information will be missed.

If the `external_id` can be added to the Discourse `WebHookUserSerializer` then I think this would be something we could include in the wp-discourse plugin.

**Comment by scossar** [comment]
If you enable the Create or Sync Discourse Users on Login option (found under SSO/SSO Provider) the Discourse Username will be automatically filled in when a user logs in to WordPress.

**Comment by mattdm** [comment]
@scossar We're using OpenID for login, and it seems like that option is only available when using DiscourseConnect. Is there another way? Filling them in manually is pretty annoying.

We _do_ allow users to edit their email address (distinct from the SSO) on the Discourse sites, but the user id is guaranteed to be the same.

**Comment by angusmcleod** [comment]
Hey @mattdm, could you clarify a few things:

1. A user's email may be different between their accounts on wordpress and discourse?
2. What do you mean that "the user id is guaranteed to be the same."? Which user id are we talking about?
