### ISSUE TITLE
get_date_from_gmt not working if non-GMT times are used

### ISSUE THREAD

**Issue by LukasReschke** [discourse/wp-discourse#238]
We have the case where  non-GMT times are used, so at:

https://github.com/discourse/wp-discourse/blob/425a2f09eca8a585edbaeafea8212e20108165da/templates/comments.php#L70

`$post->created_at`: `2016-07-19T13:16:37.356Z`

When running `get_date_from_gmt` over it this will return 1970 instead of the right date. Is it really necessary to use the `get_date_from_gmt` function here? I have removed the `get_date_from_gmt` and it is working like a charm now.

**Comment by scossar** [comment]
Can you add some examples of non-GMT times? When I use the time you supplied as the argument for `get_date_from_gmt` I get "2016-07-19T13:16:37.356Z".

**Comment by scossar** [comment]
This will be in the next update. Thanks!
