### ISSUE TITLE
Why recent releases available from wordpress.org are not tagged in the git repo?

### ISSUE THREAD

**Issue by steko** [discourse/wp-discourse#241]
I have recently upgraded the plugin from 0.6.0 to 0.9.0 (and 0.9.3 today) after being prompted by my WordPress install. I assume the newer versions are made available at the wordpress.org directory, but why aren't there tags for those releases in the git repo?

**Comment by scossar** [comment]
That will be fixed soon. The work is now all on the beta branch of the git repo.

**Comment by steko** [comment]
Thanks for the clarification!
