### ISSUE TITLE
regression in show existing WP comments feature

### ISSUE THREAD

**Issue by pjv** [discourse/wp-discourse#242]
@scossar in your commit # 51431da8fecbb7f6f1cdb602076929cdc0106e9c in refactoring `lib/discourse.php` you created `lib/discourse-comment.php` and moved the relevant code into it.

In that moved code you made some changes in one of my features that broke something and before I submit a new PR to fix it, I would like to understand if I can why you changed it the way you did so I don't inadvertently break something else myself.

In my original code there is a line that looks like this:

`if ( ! $options['show-existing-comments'] || $num_WP_comments == 0 ) {`

In the commit referenced above you changed it to this:

`if ( ( isset($options['show_existing_comments'] ) && ! $options['show-existing-comments'] ) ||
			     $num_WP_comments == 0 ) {`

And in the current v. 0.9.3 of the plugin it looks like this:

`if ( ! isset( $options['show-existing-comments'] ) ||  0 === intval( $options['show-existing-comments'] ) ) {`

The result of that current code is that when there are no existing wordpress comments and you choose the option of showing existing wordpress comments beneath the discourse comments, you get an (unwanted) empty section of wordpress comments PLUS the native wordpress comment box.

**Comment by scossar** [comment]
Thanks! If you access the value without checking if it is set it will
generate an 'Undefined index' notice. (with WP_DEBUG set to true.) It looks
like it should be good to just add `|| 0 === $num_wp_comments` to the end
of the conditional.

**Comment by pjv** [comment]
Thank you. It does look like that's all that would be needed, but unfortunately I still get the same behavior, so I think that maybe something got broken somewhere along the way in getting the number of existing WP comments. I'll start debugging and submit a PR when I figure it out.

**Comment by scossar** [comment]
The coding style is because we are trying to comply with the WordPress coding standards: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards. It's failing in a few places now, but the goal is to get it to pass.

**Comment by scossar** [comment]
The problem might be that `===` is not the same as `==` so `0 === ''` is false and `0 === null` is false.

**Comment by pjv** [comment]
Yup, using `==` seems like it is working. I'll push a PR to fix in a bit.
