### ISSUE TITLE
Is it possible to translate the messages?

### ISSUE THREAD

**Issue by steko** [discourse/wp-discourse#251]
I'm using the plugin on blog in Italian and the linked Discourse forum is in Italian too. I couldn't find a way to customize the message strings or to contribute a translation.

**Comment by scossar** [comment]
The plugin is mostly localized, there are a couple of places that it isn't, but that can be fixed. I just noticed that the text 'Originally published at' that is sent to Discourse with the topic, is not internationalized. That will get fixed this week.

You can change the internationalized message strings in your `functions.php` file by adding a function like this:

```php
add_filter( 'gettext', 'change_comments_number_text', 20, 3 );
function change_comments_number_text( $translated_text, $text, $domain ) {
    switch ( $translated_text ) {
	case 'Leave a reply' :
        	$translated_text = __( 'Please leave a reply', 'wp-discourse' );
		break;

	case 'Reply' :
		$translated_text = __( 'Response', 'wp-discourse' );
		break;

	case 'Replies' :
		$translated_text = __( 'Responses', 'wp-discourse' );
		break;
    }

    return $translated_text;
}
```
see: https://codex.wordpress.org/Plugin_API/Filter_Reference/gettext

If you want to contribute a translation, that would be great!

**Comment by scossar** [comment]
In regard to contributing a translation, I am hoping to make all the text that is in the plugin's html templates configurable on the plugin's settings page. This is quite a simple change to make. This means that the priority for translation would be to translate the text for the plugin's admin section. The user facing text will all be able to be translated/customized by the site administrator on the plugin's settings page.
