### ISSUE TITLE
Local onebox avatar url in comments

### ISSUE THREAD

**Issue by MarkoKaartinen** [discourse/wp-discourse#255]
I noticed that if the article comment has oneboxed link to my own discourse in WordPress avatar does not work right.

Example: https://it-nurkka.fi/tiedotteet/mita-artikkeleita-sina-haluaisit-tanne/
It has avatar code: `<img alt="" width="20" height="20" src="/user_avatar/keskustelu.it-nurkka.fi/marko/40/2_1.png" class="avatar">`

So as you can see it works inside discourse: https://keskustelu.it-nurkka.fi/user_avatar/keskustelu.it-nurkka.fi/marko/40/2_1.png
But not inside WordPress: https://it-nurkka.fi/user_avatar/keskustelu.it-nurkka.fi/marko/40/2_1.png

It should have the full url.

**Comment by scossar** [comment]
There are a few issues with displaying avatars. I'm going to look at this in the next couple of days. Hopefully there can be an improvement in the next update.

**Comment by scossar** [comment]
The problem is with the image `src` that's being returned by Discourse. Hopefully something can be done to fix it.
A temporary solution is to add some css to your theme's css file. Something like this should work:

```
.discourse-comments-area .quote .avatar {
    display: none;
}
```

**Comment by MarkoKaartinen** [comment]
Hmm.. That is odd since I just tested again with this: https://it-nurkka.fi/ohjeet/tilapaisten-tiedostojen-poistaminen-windows-10-kayttojarjestelmassa/

It has a relative path this time also. I have custom comment output like this in my themes functions.php:

`function custom_discourse_comment( $input ) {
    ob_start();
    ?>
	
	<div class="media">
		<div class="media-left">
			<a href="{comment_url}">
				<img class="media-object" src="{avatar_url}" alt="{username}" style="width:64px; height:64px;">
			</a>
		</div>
		<div class="media-body">
			<h4 class="media-heading">{username} <small><a href="{comment_url}">{comment_created_at}</a></small></h4>
			
			{comment_body}
						
		</div>
	</div>
	
	<?php
$output = ob_get_clean();
return $output;
}
add_filter( 'discourse_comment_html', 'custom_discourse_comment' );`

**Comment by scossar** [comment]
>I was using gravatar
That's probably what was going on.
