### ISSUE TITLE
SSO disabled following each wp-discourse auto-update

### ISSUE THREAD

**Issue by samtuke** [discourse/wp-discourse#256]
It appears that SSO is being silently disabled following each auto-update of the wp-discourse plugin. This appears to have happened twice on our wordpress server now, for the last two auto updates applied. It took time to a) recognise that this was not functioning and b) determine that the problem was as simple as SSO being disabled on wp-discourse. SSO was still enabled on discourse so logins were failing (users with active cookie logins and admins remained unaffected). Running Discourse 1.4.6 and wordpres 4.4.2.

**Comment by scossar** [comment]
Thanks for letting me know. I'll look at that today.

**Comment by scossar** [comment]
So far, I can't reproduce this when manually updating the plugin. The way the plugin stores its options has changed for versions >=1.0.0. To make updating from versions <1.0.0 easier, it runs a function that checks for the presence of the old `discourse` options array, transfers these options to the new options arrays, and the deletes the old `discourse` options array. My guess is that you had an old version of the plugin installed and that something is going wrong with the update when it is run as a background process during an automatic update. 

Do you have wp-cli installed on your server? http://wp-cli.org/

If so, you could try running the command:

`wp shell` to open a PHP console

then run:

`get_option('discourse');`

If doing that returns an array, run the command:

`delete_option('discourse');` to delete the old options.

Let me know how it goes. I'll be updating the plugin later today or early tomorrow, so please check to see if SSO has been disabled.

**Comment by samtuke** [comment]
Thanks @scossar. We're not using wp-cli on this server (unfortunately), however I will certainly keep eyes peeled for the new release and it's effect.

**Comment by scossar** [comment]
I'll let you know when I do the update.

**Comment by scossar** [comment]
I've just updated the plugin to version 1.1.1. Can you check if your SSO setting is still enabled?
