### ISSUE TITLE
import existing forum topic to new blog entry

### ISSUE THREAD

**Issue by adrelanos** [discourse/wp-discourse#258]
Sometimes a new forum post is created, that would have been better as a new blog post.

A feature to import a forum post into a new wordpress draft/unpublished post would be great!

**Comment by Grexy** [comment]
there is a plugin for this that still works as i use it on my site.  However it has not been updated in quite some time.  you will also probably have to modify the templates a bit to work with your theme.  https://meta.discourse.org/t/plugin-for-embedding-discourse-topics-in-wordpress-pages-or-posts/30228

But it would be nice to have this feature in the offical wp-discourse plugin.

**Comment by erlend-sh** [comment]
@scossar also made his own plugin related to this: https://github.com/scossar/wordpress-discourse-topic

I'm not convinced any this needs to be in wp-discourse though. You should follow up with the authors of the stand-alone plugins if something isn't working as expected.
