### ISSUE TITLE
Can we use this plugin to use Discourse's authorization instead of WP?

### ISSUE THREAD

**Issue by forumosa** [discourse/wp-discourse#259]
I would like to have multiple Wordpress blogs whose comments are handled by a single installation of Discourse. I have not seen this discussed and I am afraid this means that this plugin only helps one-WP installation for one-Discourse installation.

Can you point me in any direction or point out any technical issue that would make Many-WP/1-Discourse a bad idea? If this plugin isn't appropriate for accomplishing that set up, I would probably look to hire someone to create such a plug-in.

Thank you for looking into this.

**Comment by erlend-sh** [comment]
What you're describing is essentially a sub-task of #257 . You should follow the progress of that PR. Additional work might be required to accomplish the exact workflow (with multiple sites) you have in mind though.
