### ISSUE TITLE
Idea: Adding (unit) tests?

### ISSUE THREAD

**Issue by iamntz** [discourse/wp-discourse#261]
Right now I'm about to start changing the code structure a bit in order to match the PSR loader (so basically file names and namespaces). Althoug I'm a bit afraid to not break stuff, I'm confident enough that will work.

However, I was thinking: since the plugin grows nicely, how about we adding (some) automated tests? 

Either unit tests, by mocking all WP like described here:
https://carlalexander.ca/introduction-wordpress-unit-testing/

Or functional tests, by using the WP lib, like described here:
https://pippinsplugins.com/unit-tests-wordpress-plugins-setting-up-testing-suite/

I'm still new at this game and learning by doing, but I think it's a good thing to have some kind of automated testing for big(ish) features.

So, what do you guys think? We should start doing this? 

🖖

**Comment by scossar** [comment]
It may have been a mistake to move away from the WordPress coding standards. Other than the autoloader, I don't see any advantage from doing it. One thing we loose from doing it is that the plugin will not be considered for being installed wordpress.com VIP sites. I don't know how big a deal this is, but maybe hold off on renaming the class files for now. 

If you can figure out a good way to test the parts of the plugin that are interacting with Discourse, that would be great!

**Comment by iamntz** [comment]
> It may have been a mistake to move away from the WordPress coding standards. Other than the autoloader, I don't see any advantage from doing it. 

I'll think of a way of reverting then and make it compatible :)

**Comment by scossar** [comment]
Unit and integration tests have been added to the plugin. I'll add some details to the README about how they have been setup.
