### ISSUE TITLE
expired nonce while trying to link WP account to Discourse

### ISSUE THREAD

**Issue by simevo** [discourse/wp-discourse#266]
Hi, I installed the wp-discourse plugin and it works ("You are connected to Discourse!").

I am now trying to configure login to WP with discourse as SSO provider.

On http://wordpress.example.com/wp-admin/admin.php?page=wp_discourse_options&tab=sso_options I have:
- Enable SSO Client.
- Add "Login with Discourse" on the login form
- SSO Secret Key

In http://discourse.example.com/t/admin/site_settings/category/login I have:
- enable sso provider
- verbose sso logging
- sso secret

When I try to log in on WP with the "Login with Discourse", it says "There is already an account registed with the username supplied by Discourse. If this is you, login through WordPress and visit your profile page to sync your account with Discourse"

But when I log in on WP with my WP account proper, then go to http://wordpress.example.com/wp-admin/profile.php and click on "Link your account to Discourse" it goes to http://wordpress.example.com/?discourse_sso=1&redirect_to=http://calomelano.it/wp-admin/profile.php, that immediately gets rewritten as http://wordpress.example.com/wp-login.php?discourse_sso_error=expired_nonce, bounces back to the WP login form and says "Expired Nonce":

![spectacle j13706](https://cloud.githubusercontent.com/assets/8254819/23546500/1e14905e-0000-11e7-9d27-043d68f94de8.png)

Inside `/var/www/discourse/log/production.log` on the discourse docker image I find:
```
Started GET "/session/sso_provider?sso=bm...&sig=09..." for w.x.y.z at 2017-03-03 09:58:29 +0000
Processing by SessionController#sso_provider as HTML
  Parameters: {"sso"=>"bm...", "sig"=>"09a..."}
Redirected to http://wordpress.example.com/wp-admin/profile.php?sso=bm...&sig=f4f...
Completed 302 Found in 15ms (ActiveRecord: 5.2ms)
```

whereas in wordpress.example.com inside the weserver log (/var/log/nginx/access.log) I find:
```
w.x.y.z - - [03/Mar/2017:10:58:29 +0100] "GET /?discourse_sso=1&redirect_to=http://wordpress.example.com/wp-admin/profile.php HTTP/1.1" 302 5 "http://wordpress.example.com/wp-admin/profile.php" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36"
w.x.y.z - - [03/Mar/2017:10:58:29 +0100] "GET /wp-admin/profile.php?sso=bm...&sig=f4... HTTP/1.1" 302 5 "http://wordpress.example.com/wp-admin/profile.php" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36"
w.x.y.z - - [03/Mar/2017:10:58:29 +0100] "GET /wp-login.php?discourse_sso_error=expired_nonce HTTP/1.1" 200 1590 "http://wordpress.example.com/wp-admin/profile.php" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36"
```

Any idea ?

**Comment by scossar** [comment]
It looks like you have everything configured correctly. What happens if you try to login through Discourse with an account that does not yet exist on WordPress? I'm wondering if the redirect to `admin/profile.php` is causing the problem.

**Comment by simevo** [comment]
I get "Expired Nonce" too.
Is it supposed to create a new account in WP ?
Because that may well be impossible to do here: this is a multisite WP install, so even from WP admin for wordpress.example.com I can only add existing network users, and I can not add new user !

**Comment by scossar** [comment]
> this is a multisite WP install

That will be the problem. As it's setup now, it's not going to work with a multisite install. I'll take a look at seeing what can be done to get it working.

**Comment by simevo** [comment]
To work around this issue we can also migrate this specific WP site from multisite to a dedicated WP instance.
For the wp-discourse plugin it's probably enough to mention in the docs somewhere that multisite WP installs are not supported ATM. 
Unless of course you find that it's not too difficult to get it working. If you want to pursue that route, we can try things here (you can even get ssh access to the discourse instance if that helps).

**Comment by scossar** [comment]
The plugin should work with multisite for everything except using Discourse as the SSO provider for WordPress. I'll add that to the docs. I think it will be possible to get this to work, but it's going to be a few days until I can look at it.

**Comment by simevo** [comment]
Hi did you discover anything new or should we just close this one because it's unfeasible to get it to work ?

**Comment by scossar** [comment]
It's still something I want to get working. Leave this open for now.

**Comment by scossar** [comment]
What version of the wp-discourse plugin have you tried this with?

I have it working with multisite on my local computer without any problems (using wp-discourse 1.3.5). I don't have an online multisite setup to test it on right now. I'll see if I can find the time to set one up tomorrow.

**Comment by scossar** [comment]
I setup a multisite installation on Bluehost using a subdomain install with a wildcard subdomain and WP Discourse version 1.3.4 (the version in the WordPress plugin repo). So far everything works as expected when using WordPress as the SSO client. I'll test it out some more to be sure.

**Comment by scossar** [comment]
I've looked at this some more. There's an issue with having a single user register for multiple sites on a multisite network. There's also a problem that if multiple forums are used to authenticate users on a multisite network, the `discourse_sso_user_id` value can't be guaranteed to be unique. I think both of these problems can be solved.

**Comment by simevo** [comment]
Hi, any news ? Is there anything we can do to help ?

**Comment by scossar** [comment]
I'll look at it today.

**Comment by scossar** [comment]
The issue with the expired nonce probably isn't being caused by it being a multisite install. When I tested it locally I didn't have that problem.  Could you check what version of mysql is installed on your server? There are some details about the problem in this post: https://meta.discourse.org/t/wordpress-as-sso-client-expired-nonce/62295/15?u=simon_cossar

I still need to go over the code and make sure it isn't doing anything weird in a multisite install.

**Comment by simevo** [comment]
The wordpress site is running debian stable (6.0 jessie), hence it has [mysql 5.5.55](https://packages.debian.org/jessie/mysql-server), after the [debian stretch (7.0) release](https://lists.debian.org/debian-devel-announce/2017/05/msg00002.html), that will be updated, and the mysql version will bump to [mariadb 10.1](https://packages.debian.org/stretch/default-mysql-server).

According to the conversation on meta.discourse.org you linked, mariadb 10.0 should be enough to solve the issue, so I'll let you know in a few weeks if 10.1 solves the problem for me as well.

Many thanks for investigating.

**Comment by scossar** [comment]
I've spent some time trying this out. For the case of a single forum connected to a network of sites, everything works. For the case of multiple forums connected to multiple sites on a network, it gets a little complicated. I think it can be done, but to be done safely it will require removing the ability for a user to edit their email address through WordPress.

In the short term, I'm going to disable the ability to use WordPress as the SSO client for Discourse in multisite installations unless the 'multisite_configuration' option is enabled through the main site in the network. When that option is selected, it will only allow sites in a multisite network to connect to the Discourse forum that has been configured through the main site.

**Comment by scossar** [comment]
Using Discourse as the SSO provider for multisite WordPress is now enabled if the Multisite Configuration option is enabled on the WP Discourse Network Admin page. This only covers the case of one Discourse forum connected to multiple WordPress subsites.
