### ISSUE TITLE
Clarify the meaning of a confusing string in https://github.com/discourse/wp-discourse/blob/master/admin/configurable-text-settings.php

### ISSUE THREAD

**Issue by ujdhesa** [discourse/wp-discourse#267]
Hello,

Could the string `More replies 'more' text` be reworded to clarify the meaning? If that is not possible, could a translators' comment be added for that same purpose? I expect other locales having trouble to guess its meaning.

**Comment by scossar** [comment]
Sure. An example of when it is used is if there are four comments being displayed on WordPress, but there are 10 replies to the post on Discourse. That will add the text '6 more replies' underneath the comments section.

**Comment by ujdhesa** [comment]
I apologise for asking something which could be evident if you see it live, in action. 
In any case, since this seems to be a kind of tooltip or explanation, it doesn't suffer from menu space restrictions, so it could be elaborated a bit more, right there, in its place.

P.S. There's another "monster" string: `Custom comment meta datetime string format (default: \"`… :).  Those 6 words in a row, without any article or preposition are a bit scary to language used to concatenate using articles or preposition or both. Sometimes you get the meaning, sometimes you think you did.

**Comment by scossar** [comment]
Thanks! I'll see what I can do to make both of these descriptions clearer.

**Comment by scossar** [comment]
Thanks for bringing this up! The descriptions have been updated. Let me know if there are any more issues.
