### ISSUE TITLE
 Undefined property error

### ISSUE THREAD

**Issue by tophee** [discourse/wp-discourse#269]
O am getting the following PHP notice:

[05-Apr-2017 14:45:37 UTC] PHP Notice:  Undefined property: stdClass::$id in /var/www/html/wp-content/plugins/wp-discourse/templates/comments.php on line 67

Running the latest version from the wordpress.org repo.

Let me know if you need any other information.

**Comment by scossar** [comment]
Thanks! I thought I fixed that. I'll fix it for the next release.

**Comment by tophee** [comment]
I don't know is this is related or a separate issue, but although I have set "Default Discourse Category" to something else, when I edit a post, it is set to uncategorized...

**Comment by scossar** [comment]
> I thought it would be applied every time I edit the post as long as the post has not yet been published to discourse.

The default category is used to set the initial value of the category select input on the post-edit page. When you publish a post or save a draft, whatever value you have the select input set to will be saved. If you haven't changed it from the default value, you should keep getting the default value there.

**Comment by tophee** [comment]
>  If you haven't changed it from the default value, you should keep getting the default value there.
Yes, my point was that it would be better if you could change the default category for all posts not yet published to discourse by changing the  "Default Discourse Category" setting.

**Comment by scossar** [comment]
I'm not sure about that. It could cause problems if a post had been
scheduled to be published in a specific category.

Thanks for the initial bug report in this thread. It somehow got missed in
the last update. Hopefully you're not seeing that notice on the front end
of a live site. If so, make sure that WP_DEBUG is set to false on your
production site.

**Comment by scossar** [comment]
This has been fixed in the latest release - 1.3.5.
Thanks!
