### ISSUE TITLE
Possible bug: using WordPress as SSO provider, logging in redirects to /wp-admin

### ISSUE THREAD

**Issue by tnorthcutt** [discourse/wp-discourse#275]
I have a Discourse install and a WordPress site, with settings configured such that the WP site is the SSO provider. 

- When clicking "Log In" on the Discourse install, I'm taken to the WordPress `/wp-login.php` page as expected.
- After logging in, I'm taken to the WordPress `/wp-admin` page, instead of to the Discourse install
- If I then manually visit the Discourse install, I'm not logged in, and clicking "Log In" repeats this process.

This is with the default `twentysixteen` theme active, and only the `wp-discourse` plugin active.

Any ideas on how to proceed from here?

Here are screenshots of the settings pages:

![image](https://cloud.githubusercontent.com/assets/796639/25294041/a640949e-269a-11e7-8766-05d9fb5c0114.png)

![image](https://cloud.githubusercontent.com/assets/796639/25294054/b89421b0-269a-11e7-928f-070ad4bde4d7.png)

![image](https://cloud.githubusercontent.com/assets/796639/25294084/d9f5cce6-269a-11e7-990b-a0face13da83.png)

**Comment by scossar** [comment]
Is this something that was working previously for you, or is this the first time setting up WordPress as the SSO provider for your forum?

**Comment by tnorthcutt** [comment]
@scossar first time for **this** forum & **this** WordPress site, though I've set it up for a few others successfully.

**Comment by scossar** [comment]
When you click the login button on Discourse and are redirected to the WordPress `login.php` page, does the URL in the browser contain the string `/wp-login.php?redirect_to=` ?

**Comment by scossar** [comment]
Do you have any redirects setup on your forum's domain? Possibly it's a similar situation to this: https://meta.discourse.org/t/redirected-to-wordpress-dashboard-after-discourse-login/60116/8?u=simon_cossar

**Comment by tnorthcutt** [comment]
@scossar yes, sorry - should have included that information. Here's the url portion after the domain name, with some portions redacted (not sure if this is a security concern ¯\_(ツ)_/¯ ):

`/wp-login.php?redirect_to=%2F%3Fsso%3Dbm9uY2U9OTlmZjQ0[redacted]kYTgzYmMyYWMwNmYmcmV0dXJu%250BX3Nzb191cmw9aHR0cCUz[redacted]W11bml0eS52YXBlbWVudG9ycy5j%250Bb20lMkZzZXNzaW9uJTJGc3NvX2xvZ2lu%250B%26sig%3D9909fa7ef3[redacted]96c42b0546374[redacted]277c7b7b24

**Comment by scossar** [comment]
Are the sites using https?

**Comment by tnorthcutt** [comment]
They are able to, but it is not forced (e.g. the WP admin pages load at both http and https)

**Comment by tnorthcutt** [comment]
My Discourse install is available at both `community.domainname.com` and at `domainname.discoursehosting.net`.

I tried the workaround in that Discourse thread you linked above, to no avail:

```php
function your_namespace_allow_extra_redirect( $hosts ) {

	$hosts[] = 'community.domainname.com';
	$hosts[] = 'domainname.discoursehosting.net';

return $hosts;
}
add_filter( 'allowed_redirect_hosts', 'your_namespace_allow_extra_redirect' );
```

**Comment by tnorthcutt** [comment]
Sorry, the workaround does seem to be helping now; was probably caching-related before.

Any ideas on a permanent/non-hacky solution?

**Comment by tnorthcutt** [comment]
Heh, I spoke too soon. It worked on our _staging_ site, but not production, where I'm also having to use the login page path setting:

![image](https://cloud.githubusercontent.com/assets/796639/25299446/7b5e1202-26bc-11e7-8264-923f5e0d5f7e.png)

**Comment by scossar** [comment]
Are there any plugins installed on your production site that aren't on the staging site?

**Comment by tnorthcutt** [comment]
Yes - between my last posting and now, I believe I've narrowed it down to Paid Memberships Pro causing a problem. I suppose it's hijacking the redirect. I'm terribly sorry to have wasted your time on this; I appreciate your attention to it. I'll try to help with other issues on this repo to make up for it in some way; if there are particular ones you want eyes on please point me to them.

**Comment by scossar** [comment]
No problem at all. I'm curious about how the plugin is working with discoursehosting.com sites. Could you confirm whether or not this code is required to get SSO working on your site?

```
function your_namespace_allow_extra_redirect( $hosts ) {

	$hosts[] = 'community.domainname.com';
	$hosts[] = 'domainname.discoursehosting.net';

return $hosts;
}
add_filter( 'allowed_redirect_hosts', 'your_namespace_allow_extra_redirect' );
```

**Comment by tnorthcutt** [comment]
I'm not sure what you're asking 😕. I have that code in place, but I still get redirected to `/wp-admin` instead of back to e.g. `community.domainname.com`.

If I disable Paid Memberships Pro, it works as desired.

**Comment by scossar** [comment]
If you remove that code and disable Paid Memberships Pro does it still work? My guess is that it won't.

**Comment by tnorthcutt** [comment]
You are correct; with PMP disabled and that code not present, it does not work; instead it redirects to `/wp-admin`.

By chance does that provide a clue as to how to get it working _with_ that code present and _with_ PMP enabled?

**Comment by scossar** [comment]
Thanks! An option is going to have to be added to the plugin to allow for redirecting to domains other than the one that's obtained from the 'Discourse URL' option.

For now, just use the code I provided.

The problem with the PMP plugin is a separate issue. Does it give you an option to not set a login redirect? If not, there's probably a simple solution, but I'd have to see the plugin's code.

**Comment by tnorthcutt** [comment]
It does not; their GitHub repo is here: https://github.com/strangerstudios/paid-memberships-pro

I'm going to open an issue there and link to this one for tracking.

**Comment by scossar** [comment]
Here are a couple of solutions - only tested locally. The first one should leave the PMP login redirect in place except for when it's an SSO request. This should be tested a little more (replace 'testeleven' in the function name and `add_filter` statement with something that's unique to your site):

```php
function testeleven_pmp_login_redirect( $redirect_to, $request, $user ) {
	if ( strpos( $request, 'sso' ) !== false ) {
		$redirect_to = $request;
	}

	return $redirect_to;
}
add_filter( 'pmpro_login_redirect_url', 'testeleven_pmp_login_redirect', 10, 3 );
```
This one will completely remove the PMP login redirect for all requests:

`remove_filter('login_redirect','pmpro_login_redirect', 10, 3);`

Use one or the other of these methods, not both.

**Comment by tnorthcutt** [comment]
@scossar you are a gentleman and a scholar. This works; thank you.

**Comment by tnorthcutt** [comment]
@scossar would you like a PR to add this fix to the plugin, with a compatibility check to see if PMP is active first?

**Comment by scossar** [comment]
Yes, one way to approach it would be to add something like this to the end of `SettingsValidator::validate_enable_sso`, before the return statement. This will display an error message after SSO is enabled, if a plugin is hooking into the `login_redirect` filter. (The message should be more helpful than the one I've added here.) This way we're not limited to trying to make a special case for every possible plugin that might be installed.

```php
if ( has_filter( 'login_redirect' ) ) {
    add_settings_error( 'discourse', 'sso_provider_redirect_conflict', ( 'There is a plugin installed on your site that is adding a login redirect, this may cause problems with SSO between your site and Discourse...' ) );
}
```
