### ISSUE TITLE
Limit SSO to specific users?

### ISSUE THREAD

**Issue by sfyfe31** [discourse/wp-discourse#284]
Is it possible to limit SSO to certain users? I only want some users to be able to access Discourse for example, as it'll be used as a membership exclusive.

Just thought I should check, before starting a fork.

**Comment by scossar** [comment]
It's not possible right now, but if it would help, I can add an action to the SSO login function and pass the current_user to it. The way I've been dealing with membership plugins is to add WordPress members to Discourse groups and then control their access on the forum that way. This can be done automatically on the WordPress end, but requires extending the WP Discourse plugin. You don't need to fork it to do this.

If you find you need any action/filter hooks to do what you want, let me know and I can add them.

**Comment by sfyfe31** [comment]
We have users in Wordpress which are assigned to groups, controlling their access to certain pages. We also want to prevent users who aren't in these groups from using our Discourse forum.

Using your suggestion, it might be a case of having users with no access by default, but then using the Discourse API to programmatically add them to a privileged group, which lets them access the forum.

**Comment by scossar** [comment]
Yes, using the setup I suggested, all users would have access to the forum, but the forum would contain protected content that could only be accessed by members of the WordPress group. The forum would be a mirror of the WordPress site.

If you only need to give access to the forum to members of one group, then an easier approach would be for me to add an action to the plugin's SSO login function that you can hook into to choose whether or not to login the user, based on their group membership. Something like this (pseudocode) added to your theme or a separate plugin could work:

```php
add_action(  'wpdc_before_sso_login', 'sso_login_non_member_redirect' );
function sso_login_non_member_redirect(  $user  ) {
    if ( ! is_group_member( $user, 'your_group' ) ) {
        wp_safe_redirect( '/your-signup-page' );

        exit;
    }
}
```
I'll add that action in the next update - sometime later this week.

**Comment by tnorthcutt** [comment]
@scossar This looks great. Please let me know if you need any additional eyes or testing on this. I very frequently recommend Discourse to my membership site clients, and having a way to do this would mean I can build small plugins to integrate this behavior with each of the various membership plugins we use, so admins can select membership levels to allow access to, choose where to redirect to on failure, etc.

**Comment by lvnilesh** [comment]
Appreciate a specific example on how to use this with s2member
```
current_user_can(access_s2member_level1)
```
Thanks.

**Comment by scossar** [comment]
@lvnilesh feel free to ask about this on the meta.discourse forum.
