### ISSUE TITLE
SSO stuck in redirect loop

### ISSUE THREAD

**Issue by MatthewHolmes** [discourse/wp-discourse#286]
We had PrimeTime WP Discourse SSO plugin in place on our Wordpress install to handle the SSO to our Discourse forum and that was working apart from redirecting the user back to the Wordpress site on logout.  To fix this I tried updating to WP-Discourse 1.43.  The Wordpress site is the SSO Provider.  

Since that whenever I try to access Discourse the page gets stuck in a redirect loop.  At first it gets stuck at 
https://www.mydomain.com/?sso=bm9uY2U9NDk3NzQ5MmY4M2Q2MmVjNjRjOTM...&sig=2ec83b391a3cecd44d9123563a237d7f881...
(... being the rest of the string)

Refreshing the page again will get to:
https://forum.mydomain.com/session/sso_login?sso=bm9uY2U9NDk3NzQ5MmY4M2Q2MmVjN...&sig=2ec83b391a3cecd44d9123563a237d7f88132d0d...
But we get the message Login Error. Account login timed out, please try logging in again.

I've tried deactivating WP-Discourse and reactivating PrimeTime WP Discourse SSO without any success.  We are using the MemberPress plugin on Wordpress which does have a custom login page, but this problem occurs even when that is deactivated.  We haven't changed any of the Discourse settings other than getting an API key.  Now I can't login there to make changes.  Hope someone can offer some advice.

**Comment by scossar** [comment]
I think this was resolved on the forum. If you're still having trouble, let me know.

**Comment by MatthewHolmes** [comment]
Yes thanks Simon, all resolved.
