### ISSUE TITLE
Wordpress version compatibility issue

### ISSUE THREAD

**Issue by maartee** [discourse/wp-discourse#287]
The plugin information says: 
"Requires WordPress Version: 4.4 or higher"
Because it uses wp_parse_url() function with two parameters, it is presumably not compatible with WPversions older than 4.7. 
More information here:
https://developer.wordpress.org/reference/functions/wp_parse_url/#changelog

The affected code is in wp-discourse/lib/discourse.php:
$domain_name   = wp_parse_url( $discourse_url, PHP_URL_HOST );

With my 4.4.2 WP, it returns 'Array' string instead of domain name.

Please can you verify and possibly update the compatibily info?
Thank you, this plugin is great!

**Comment by scossar** [comment]
Thanks for finding that!

**Comment by scossar** [comment]
I've updated the version in the readme.txt file.
