### ISSUE TITLE
SSO Causing Loss of Access to Backend

### ISSUE THREAD

**Issue by tom-nagle** [discourse/wp-discourse#288]
I recently migrated my site from GoDaddy (where this wasn't an issue) to SiteGround.  I had my website act as the SSO provider, since I have a paywall.  

Now, I lose access to the back end of my wordpress site due to the plugin.  I had to disable the plugin initially to regain access, but found that this doesn't happen when the "Enable SSO Provider" option is disabled (which doesn't meet my needs for how I have site set up).

I've tested this with multiple browsers and devices.  Using the admin login credentials with SSO disabled, I get sent immediately to my back end.  With SSO enabled (when the plugin is still active), I get redirected back to the login screen.  But, I am logged in and can access protected content as a user browsing the front end, but cannot get to the admin areas.
![sso error](https://user-images.githubusercontent.com/32239456/30782307-82c0b020-a0fd-11e7-9c92-5628edbb0d36.png)

**Comment by scossar** [comment]
What are the versions of php and WordPress on your server?

**Comment by tom-nagle** [comment]
Thanks for the response.

I have version 7.0.23 for php, though have an option to move to 7.1.9, as well as move down to the 5.5/.6 versions.

My Wordpress version is 4.8.2.

Tom

Tom Nagle, PhD
Founder & Manager
Strategy Connections, LLC
571-969-8666
StrategyConnections.com<https://strategyconnections.com/>

**Comment by scossar** [comment]
Thanks. Php 7.0.23 if fine and won't be causing the issue. 

Do you have the WP Discourse option 'Create Discourse User on Login' enabled? If so, could you try logging it with it disabled?

**Comment by tom-nagle** [comment]
That actually fixes the issue with admin access – I go right to the back end when I login.

Though like I said, I didn’t have this issue before I switched providers for some reason.  The creation of the discourse user is kind of important for the business model I’m using.

Tom Nagle, PhD
Founder & Manager
Strategy Connections, LLC
571-969-8666
StrategyConnections.com<https://strategyconnections.com/>

**Comment by scossar** [comment]
That's great. It narrows down the problem.

Did you install any new plugins when you migrated the site?

With the Auto Login feature, have you set a path in the Redirect After Discourse Login field? There could be an issue with redirecting to the user's profile page.

**Comment by scossar** [comment]
It looks like the backend of your site is using HTTPS, but the front end is using HTTP. Has it always been setup this way?

**Comment by tom-nagle** [comment]
I tried it both with the redirect and without it – it didn’t make a difference.

I did install Analytify Pro (google analytics).  I also added the free version of Cloudflare and planned on upgrading to their pro plan.

I seem to be having some issues with the https/http when I added Cloudflare.  I was planning on working through that tomorrow.  That could be related – I noticed it the same day.  I was told to wait 24 hours (this was Friday) for the DNS to update to see the https on the front end again, but it hasn’t happened yet.

Before I migrated, I had https for both front and back end.

Tom Nagle, PhD
Founder & Manager
Strategy Connections, LLC
571-969-8666
StrategyConnections.com<https://strategyconnections.com/>

**Comment by scossar** [comment]
Is SSO working between your site and Discourse?

**Comment by tom-nagle** [comment]
Yes, signing on to WordPress also gives me access to the discourse forum

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by scossar** [comment]
Give it another try when you have HTTPS configured for the front end of your site. With Auto Login enabled, if you get locked out of your site you can bypass it by appending `?skip_autologin=true` to the login query string:

`https://www.strategyconnections.com/userlogin/?skip_autologin=true`

I'm going to make some changes to the Auto Login feature very soon. Thanks for reporting this!

**Comment by scossar** [comment]
The auto-login feature has been removed from version 1.5.0. There is still an option to automatically create a Discourse user on WordPress login.
