### ISSUE TITLE
Option to "Open Start Discussion Text" and "Continue Discussion Text" Links in New Tab

### ISSUE THREAD

**Issue by clutchwave** [discourse/wp-discourse#291]
It would be great if there was an option to open these two links in new tabs, and then set a ` target="_blank"` in them. I don't want people completely disappearing off of our blog when we move to Discourse.

For the time being, I'll probably find a way to add a filter.

Thanks!

**Comment by scossar** [comment]
I'm not sure if it should be an option, but I can add a filter to the link so that you can easily add the `target` attribute.

I'll see what other people think about adding it as an option.

**Comment by clutchwave** [comment]
While I still think this should be an option, I've worked around it with a filter:

```php
function my_discourse_no_replies_filter ($html) {
        // Open the Start the Discussion link in a new tab
        $html = preg_replace('/Start the discussion at\s+<a /s','Start the discussion at <a target="_blank" ',$html);
        return $html;
}
add_filter("discourse_no_replies_html","my_discourse_no_replies_filter");
```

Not ideal but whatever, it works!

**Comment by scossar** [comment]
I've added this as an option. You can find it in the Comment Settings tab.
