### ISSUE TITLE
Link Back to Blog Post AFTER Discourse Post Truncation

### ISSUE THREAD

**Issue by clutchwave** [discourse/wp-discourse#292]
After the paragraph gets truncated in Discourse, it'd be nice to have an option for a link that points back to the blog, saying "... (read more on the _________ blog)."

![image](https://user-images.githubusercontent.com/2278974/31156292-4bb7239c-a879-11e7-9e44-196f6f7a3247.png)

Yes, there is a link up above, but it's a very small one and many will miss it. So it'd be cool to have more. This is likely something we'll end up hacking into the plugin ourselves, but would be great to get rolled into the real branch. Am willing to bounty.

Thanks!

**Comment by scossar** [comment]
The small text size is set on Discourse. You can change it with some custom css on your forum. For creating a link back to WordPress, you can customize the template that's used to publish posts. See this topic: https://meta.discourse.org/t/wp-discourse-template-customization/50754.

You could also try selecting the Add Featured Link option. That will add a link to the WordPress post to the Discourse topic list, and to the topic's header.

**Comment by clutchwave** [comment]
The issue is that you're not giving that link a separate class, so if we modified the `<small>` CSS, it'd be universal (unless we got hacky by only modifying the *first* <small> or something). At the very least, throw a div class (or span class?) around it.

Were I to pay someone to add an *option* for my requests, would it be possible to to merge it into master? Otherwise I'd just have to do it via filter or something. Obviously I don't want to fork the code over something so small.

Thanks!

**Comment by clutchwave** [comment]
As a sub-feature, it'd also be great to include/embed the WordPress post's *featured image* above or below the Discourse excerpt that's generated, with yet another option to have that image link back to the blog post. Images always help kick discussions off nicely.

Again something I'd be happy to bounty, and could be made an option in the "Publish to Discourse" post editor area.

**Comment by scossar** [comment]
> The issue is that you're not giving that link a separate class

I'd like to be able to do that, but the class attribute is stripped out by Discourse when the post is published. The only way around it is to whitelist some classes through a Discourse plugin. I'm not sure that overriding the Discourse css for `small` tags will cause a problem. The default 9px is hard to read.

> As a sub-feature, it'd also be great to include/embed the WordPress post's featured image above or below the Discourse excerpt that's generated, with yet another option to have that image link back to the blog post. 

This can be done by customizing the `publish_format_html` template. I can do that for you if you like.

**Comment by clutchwave** [comment]
My solution has been to override `wp_discourse_excerpt`. Thanks for responding as I've been figuring this code out. Seems well done.
