### ISSUE TITLE
Minor Typo: Comment Should Say `sync_to_discourse_work`, not `sync_do_discourse_work`

### ISSUE THREAD

**Issue by clutchwave** [discourse/wp-discourse#293]
https://github.com/discourse/wp-discourse/blob/0e2b9e34019bae1b80e9de2899303a706bad94d7/lib/discourse-publish.php#L113

Just figuring out the code and saw this, no big deal

**Comment by scossar** [comment]
Thanks! Details matter. It's fixed now.
