### ISSUE TITLE
WP SSO Not Working

### ISSUE THREAD

**Issue by mikeb629** [discourse/wp-discourse#294]
Hey Simon!

Just logged into our WP site and tried to access the Discourse forum, but got the following timeout error:
<img width="360" alt="screen shot 2017-10-24 at 1 38 14 pm" src="https://user-images.githubusercontent.com/6869844/31923878-d23c8a36-b8c0-11e7-8c9c-a2fbad50bdce.png">

I've retried now with several WP accounts and get the same result. Are there any known issues with SSO currently?

Thanks!

Mike

**Comment by mikeb629** [comment]
Site is Running:
- WP-Discourse: 1.4.5
- WP: 4.8.2

**Comment by scossar** [comment]
>  Are there any known issues with SSO currently?

Not that I know of. Did this begin after updating the plugin? Have you changed anything on your site recently?

**Comment by mikeb629** [comment]
Thanks Simon. Nope it was working fine after the update, it just started today strangely enough... Was fine yesterday and nothing has changed on the site.

I'll keep trying and see if there's anything on my end triggering it.

**Comment by scossar** [comment]
If you're locked out of your forum, you should be able to access it by going to `/users/admin-login` and having Discourse send you a login email. Let me know what you find.

**Comment by mikeb629** [comment]
Thanks Simon! Back in now... Strange - I tried multiple accounts, clearing cache etc. before posting here. Gave it an hour, tried it all again and working now. Thanks for jumping on this quickly, apologies for the false alarm!

**Comment by scossar** [comment]
Maybe your forum was in read-only mode. I haven't tested SSO login for that situation. I'll take a look at it.

**Comment by mikeb629** [comment]
No setting were changed on the Discourse side of things (or WP for that matter)... I guess it could go into read-only if there was an update being processed? We're running on Discourse.org hosting.

**Comment by scossar** [comment]
I think there were some issues with Discourse hosting last night, so that's probably what was going on. Let me know if you have any more problems with this.
