### ISSUE TITLE
Error 403 with Discourse as SSO host

### ISSUE THREAD

**Issue by ohmycrypto** [discourse/wp-discourse#295]
I just set up WP discourse + SSO according to the instructions here:
https://meta.discourse.org/t/wp-discourse-plugin-installation-and-setup/50752

When trying to login with the shortcode [discourse_sso_client login='Login Through the Forum'] I get an error:

You don't have authorization to view this page.
HTTP ERROR 403

I am using WP Rocket + cloudflare

URL: cannabisanbauen.net

**Comment by scossar** [comment]
Anything you can report back about this issue would be greatly appreciated. Do you have any security related plugins, for example Wordfence, activated on your site?

**Comment by ohmycrypto** [comment]
No wordfence activated.
Is there any way to send you a system report including all plugins installed etc?
Here is a test link with the shortcode:

https://www.cannabisanbauen.net/test-forum-login/

**Comment by scossar** [comment]
Thanks, I setup an account on your forum. I tried the login link and got the same error. 

> Is there any way to send you a system report including all plugins installed etc?

Yes, contact me through https://meta.discourse.org/. I am Simon_Cossar on that forum.

**Comment by scossar** [comment]
It seems that the issue was caused by the Block Bad Queries plugin.
