### ISSUE TITLE
v. 1.5.1 not finding my admin account on discourse

### ISSUE THREAD

**Issue by pjv** [discourse/wp-discourse#296]
I'm getting the `There is no admin user on Discourse with the email address...` error message on the SSO provider tab, but my WP email address is definitely a valid discourse admin user with which I can successfully log in to Discourse through WP SSO.

I also noticed that when I tried to put the raw URL that I think the plugin is constructing into a browser, including the urlencoded email address as a query argument, Discourse is returning a list of 100 users as though the query were not part of the url. This is with Discourse v. v1.9.0.beta14 +358.

Not sure if this is a wp-discourse thing or a Discourse thing...

**Comment by scossar** [comment]
Thanks! It's a wp-discourse thing. There is a new route available on Discourse for querying users by their email address. I'm checking for the availability of the route incorrectly. I'll fix that right away.

**Comment by scossar** [comment]
I've pushed version 1.5.2 to the WordPress repo. When you get a chance, can you try it out and see if it solves the problem?

**Comment by pjv** [comment]
yup. Fixed. Thanks, and thanks for all your work on maintaining and extending wp-discourse.
