### ISSUE TITLE
Feature request: CSS class for "originally published" text above excerpt

### ISSUE THREAD

**Issue by ohmycrypto** [discourse/wp-discourse#297]
Title says it all :)

It makes it easier to customize that piece of text

**Comment by scossar** [comment]
I would like to be able to add that, but it is not possible. When the post is published from WordPress to Discourse, Discourse will strip out any css classes that are in the post. The 'originally published' text is in a `small` tag. It's the first small tag in the first post in the topic. There are ways that you can target that with css in a Discourse customization.

**Comment by ohmycrypto** [comment]
is there any other html element which would be more suitable?
https://developer.mozilla.org/de/docs/Web/HTML/Element

**Comment by omarfilip** [comment]
I've replaced the `<small>` tag with `<em>`in my instance because users have complained that the text is too small. But, it will have to be done again with every plugin update.
