### ISSUE TITLE
Feature request: placeholders for number of comments etc

### ISSUE THREAD

**Issue by ohmycrypto** [discourse/wp-discourse#298]
For non-devs it's tricky to fully customzise the output for the comments area under the post
how about a placeholder for number of discourse comments, such as %number_comments% which can be added to the text fields in wp discourse settings?

That way users don't have to replace whole html template through functions.php just to add some tiny dynamic output

**Comment by scossar** [comment]
The plugin updates the WordPress comments number with the comments number from Discourse. If your theme displays the comments number (either on the posts index page or the single post page) then the correct comments number will be displayed. 

You can output the comments number inside of the WordPress loop with `comments_number();` 

It's outside of the scope of the wp-discourse plugin to add this to a theme.
