### ISSUE TITLE
Featured link issue

### ISSUE THREAD

**Issue by jrgong420** [discourse/wp-discourse#299]
When duplicating a post, the old featured link is added to the topic in discourse

1. is there any way to change the featured link? I could not find any possibility in discourse
2. what do I have to change in the wordpress editor to "clear" the post from the old featured link? So that it generates a new featured link when publishing the post

**Comment by jrgong420** [comment]
any possible solution here?

**Comment by scossar** [comment]
How are you duplicating the post?

**Comment by scossar** [comment]
I see the problem now. The original post's metadata is being copied to the new post. There is currently no way of fixing this through the plugin's UI.

To 'unlink' the post from Discourse, you would need to delete three metadata keys from the post. If the duplicate post had an id of `58`, you would need to run these commands to clear it:

`delete_post_meta(58, 'discourse_post_id')`

`delete_post_meta(58, 'discourse_topic_id')`

`delete_post_meta(58, 'discourse_permalink')`

If you have wp-cli on your server, this is quite straightforward, if not, it's a bit of a hassle. I'll look at adding an advanced option to the Publish to Discourse metabox for unlinking a post from Discourse.

**Comment by jrgong420** [comment]
Looking forward to the new advanced option :)
I dont' wave CLI activated, but there is a workaround for discourse:
https://meta.discourse.org/t/modify-topic-featured-link/75521/5

**Comment by scossar** [comment]
Yes, I just posted that. But it still won't get around the problem of not being able to publish the cloned post as a new topic to Discourse.

**Comment by adamengst** [comment]
Just chiming in on this — we're close to spinning up a new version of a long-standing site that will use WordPress for articles and Discourse for comments. With one particular type of article, we're likely to want to do a lot of duplicating of an old post and then updating (software updates, where most of the metadata will be the same for subsequent posts). 

If my testing is accurate, this cloning issue is no longer a problem. After you clone a post, the Discourse box lets you select an Unlink from Discourse checkbox, after which you can click Save Draft, and then you can choose to create a new Discourse topic in a category of your choosing.

So, assuming I'm right, anyone finding this thread in the future can rest assured that it's no longer a problem.
