### ISSUE TITLE
Latest version not published on Packagist

### ISSUE THREAD

**Issue by LeoColomb** [discourse/wp-discourse#302]
Really strange since it's supposed to be automatic, but the latest release (1.5.6) doesn't seem to be published on [Packagist](https://packagist.org/packages/discourse/wp-discourse)...

Maybe the webhook failed?
Thanks a lot! 👍

**Comment by scossar** [comment]
Thanks! I'm not sure what happened, but I'll get it sorted out.

**Comment by scossar** [comment]
The issue was that the license identifier we were using was considered invalid. I've updated it, but may have to do some configuration on Packagist to get the latest version on there. I'll sort it out early next week. Thanks for letting us know about this.

**Comment by LeoColomb** [comment]
@scossar Hey! Thanks for your reply! 🙂 
It seems that the change regarding the license identifier doesn't resolve the issue... Do you have any output when you try to push a manual update?

**Comment by LeoColomb** [comment]
Just received the update form Packagist! => https://packagist.org/packages/discourse/wp-discourse#1.5.7 🎉 

Did you do something particular?

**Comment by scossar** [comment]
That's great! No I didn't do anything recently. Last week I changed the credentials on the Packagist service that's connected to this repo so that it uses my Packagist token. I'll keep an eye out for this with the next update.

**Comment by LeoColomb** [comment]
OK, releases are published very late on Packagist, but at least they are published. 
Closing now, but could be relevant to understand the source of this delay.

Thanks! 😃

**Comment by scossar** [comment]
This still needs to get sorted out. The current version is 1.6.8, the version on Packagist is 1.6.6.

**Comment by LeoColomb** [comment]
@scossar Oh ritgh, really strange!
That said I'm also able to see this issue with some other packages, or at least another one: Jetpack.

**Comment by LeoColomb** [comment]
https://github.com/composer/packagist/issues/200#issuecomment-350618005 may be?

**Comment by scossar** [comment]
I think the problem is that I messed up the credentials on the Packagist github hook. I'm an owner of the wp-discourse package. I'll sort it out this week.

**Comment by scossar** [comment]
It should be working properly now. The current version on Packagist is 1.6.8.

**Comment by LeoColomb** [comment]
Are you sure? 😉 
I mean, the last two version have not been published: https://packagist.org/packages/discourse/wp-discourse

**Comment by scossar** [comment]
Thanks! It's been updated to 1.8.7 now. The Github service that we were
using to publish updates to Packagist has been discontinued. I've
configured a webhook handle updates now. From now on I'll check that the
version on Packagist us updated when I push changes to Github.
