### ISSUE TITLE
What Discourse permissions does this plugin require?

### ISSUE THREAD

**Issue by dandv** [discourse/wp-discourse#304]
Just wanted to see under the **Installation Instructions** heading on [the plugin page](https://wordpress.org/plugins/wp-discourse/) what permissions are required. Apparently it's only the API key, and no special user needs to be created. But which key is OK? The Admin one, or the All Users one?

**Comment by scossar** [comment]
Thanks for the question. It's something I've been thinking about. Currently, the plugin assumes that an admin API key (either an individual admin user's key or the All Users key) will be used.

For the case where posts are being published from WordPress to Discourse by a single user, the api key of a non-admin user should be sufficient. All posts will have to be published under that user's username. This can be done now, but the documentation doesn't make it clear how to do it. I'll clean that up next week.  There are a couple of minor issues that need to be dealt with for this to work well. It seems worth doing.

**Comment by maiki** [comment]
Since 2.4.3 WP-Discourse has granular API support, and the current scopes are listed at https://meta.discourse.org/t/connect-wp-discourse-to-discourse/223490.
