### ISSUE TITLE
Special characters in wp posts encoded in discourse topic

### ISSUE THREAD

**Issue by jrgong420** [discourse/wp-discourse#306]
I found an issue with hyperlinks in wordpress posts displayed in discourse

The characters {} in hyperlinks are encoded into %7B and %7D in the discourse topic

WP Post: https://www.cannaseeds.de/sensi-seeds-gratis-jack-herer/
Link to Discourse Topic: https://forum.cannabisanbauen.net/t/sensi-seeds-gratis-3x-jack-herer-zu-jeder-bestellung-ab-60-gueltig-bis-15-04/2784

Link in WP Post: http://www.sensiseeds.com/refer.asp?refid={22444B85-CBC8-4777-89F4-B332719C1B45}&L=5

Same link in Discourse topic: http://www.sensiseeds.com/refer.asp?refid=%7B22444B85-CBC8-4777-89F4-B332719C1B45%7D&L=5

**Comment by scossar** [comment]
That seems correct to me. Is it causing an issue with the `refid`?

**Comment by jrgong420** [comment]
What do you mean by correct?

I think due to the encoding of the brackets the affiliate tracking won't work

**Comment by scossar** [comment]
I mean that it's encoding `{}` correctly. 

```
> urlencode ("http://www.sensiseeds.com/refer.asp?refid={22444B85-CBC8-4777-89F4-B332719C1B45}&L=5")
> string(104) "http%3A%2F%2Fwww.sensiseeds.com%2Frefer.asp%3Frefid%3D%7B22444B85-CBC8-4777-89F4-B332719C1B45%7D%26L%3D5"
```

Discourse is doing the encoding, not WordPress, so there's nothing the WP Discourse plugin can do about it. I think the only way around it would be to put the raw link in the WordPress post.
