### ISSUE TITLE
Call to undefined function WPDiscourse\Admin\iconv_strlen() 

### ISSUE THREAD

**Issue by davide101** [discourse/wp-discourse#307]
I'm getting this error from the plugin when saving the SSO secret: 
"Call to undefined function WPDiscourse\Admin\iconv_strlen()"

Fatal error: Uncaught Error: Call to undefined function WPDiscourse\Admin\iconv_strlen() in /home/xxx/public_html/wp-content/plugins/wp-discourse/admin/settings-validator.php:528 Stack trace: #0 /home/xxx/public_html/wp-includes/class-wp-hook.php(286): WPDiscourse\Admin\SettingsValidator->validate_sso_secret('PRGzsCQRZnP') #1 /home/xxx/public_html/wp-includes/plugin.php(203): WP_Hook->apply_filters('PRGzsCQRZnP', Array) #2 /home/xxx/public_html/wp-content/plugins/wp-discourse/admin/form-helper.php(288): apply_filters('wpdc_validate_s...', 'PRGzsCQRZnP') #3 /home/xx/public_html/wp-includes/class-wp-hook.php(288): WPDiscourse\Admin\FormHelper->validate_options(Array) #4 /home/xxx/public_html/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array) #5 /home/xxx/public_html/wp-includes/formatting.php(4314): apply_filters('sanitize_option...', Array, 'discourse_sso_c...', Array) #6 /home/xxx/public_html/wp-includes/option.php(297): sanitize_option('discourse_sso_c...', in /home/xxx/public_html/wp-content/plugins/wp-discourse/admin/settings-validator.php on line 528

Can you advise? 

Using the latest version of WordPress (4.9.4) and plugin (1.5.8).

**Comment by scossar** [comment]
Thanks for the report.  It sounds like the `iconv` extension isn't enabled on your server. It is enabled by default. This is the first time I have heard of this problem.

See: http://php.net/manual/en/iconv.installation.php

I'm not sure that the plugin needs to be using `iconv_strlen` here. `strlen` should be sufficient. All it's being used for is to validate that the SSO secret is at least 10 characters long. If you're not able to get the iconv extension enabled on your server, I can look at replacing that function call in the next update.

**Comment by scossar** [comment]
I've thought about it a bit. I'll replace that function call in the next update. It's not worth risking throwing an error for something so trivial. The update should be out by this Friday. I'll let you know when it happens.

**Comment by davide101** [comment]
Thank you, Simon! I got it working. Thank you for the quick response. :)
