### ISSUE TITLE
Update to Version 1.6.1 lost "old" comments

### ISSUE THREAD

**Issue by jasonbayton** [discourse/wp-discourse#308]
Hello, 

![image](https://user-images.githubusercontent.com/3178412/38466443-0b63614e-3b21-11e8-8536-b61b9af58c6a.png)

Prior to updating to 1.6.1 old comments and pingbacks (from wordpress) would show underneath discourse comments as expected. This no longer happens.

Wordpress 4.9.5
Here's an example post, where there should be 105 Wordpress comments: https://goo.gl/pK8eZF

**Comment by scossar** [comment]
Sorry for the delay in responding to this. When the Load Comments With Ajax option is selected, WordPress comments are not displayed underneath Discourse comments. This needs to be either fixed, or the copy for the option needs to be updated. I'll try to do something with it next week.

If you deselect the Load Comments With Ajax option, WordPress comments should still be displayed underneath the Discourse comments.

**Comment by jasonbayton** [comment]
Ah thank you so much - I didn't notice any direct change between toggling the checkbox, only after updating. That's resolved it and agree, a bit of help text in the menu there would be a great idea.
