### ISSUE TITLE
Incorrect time pulled across

### ISSUE THREAD

**Issue by jasonbayton** [discourse/wp-discourse#309]
I'll reference this immediately, as I'm seeing the same behaviour: 
https://github.com/discourse/wp-discourse/pull/162

Server date/times are correct on both, Wordpress time is correctly set and Discourse time is showing as correct, however when a comment is pulled across I'm noticing it's one hour behind since I edited the timestamp settings to show the time as well as date.

![image](https://user-images.githubusercontent.com/3178412/39655174-2e108b84-4ff0-11e8-9b5a-af713ad8eca0.png)

Has this regressed or am I missing something obvious please? :-/

**Comment by scossar** [comment]
Yes, that has regressed. It was returning 1970-01-01 when non-GMT times were used. I'll fix it to work for all cases.

**Comment by jasonbayton** [comment]
Thank you very much!

**Comment by scossar** [comment]
There was just a small update to the plugin (version 1.6.2), but it doesn't deal with this. I didn't want to try and fix it on a Friday afternoon. I'll get it done early next week.

**Comment by jasonbayton** [comment]
That's perfectly fine thank you. For the comments already pulled, will the timestamps be updated or what's the best approach there?

**Comment by scossar** [comment]
> For the comments already pulled, will the timestamps be updated?

Yes, the plugin builds the comments from `json` data that's returned from Discourse. At the moment the html that is generated from the `json` data isn't being cached. That should be changed, but it will simplify things a bit in this case. The correct time will be displayed when you get the updated code.

**Comment by scossar** [comment]
Thanks for bringing this up! The issue with the WordPress `get_date_from_gmt` function is that it fails to match the datetime returned from Discourse when UTC times are used on WordPress. In that case, it is expecting datetimes in the format used by WordPress - without any timezone information included in the date. 

I assume that on your site you have set the time by selecting a city/region from the General Settings timezone dropdown. For those cases `get_date_from_gmt` works as expected.

I'll update the plugin tomorrow with a new function for formatting the date.

**Comment by jasonbayton** [comment]
I have indeed set the timezone manually so happy to see it'll work tomorrow! I'm using discourse + wp-discourse to test the water on a live blog format I'm running today and tomorrow, hence the timestamps are important to me (as would the option to define the order of comments but I'm ok with that) - https://goo.gl/LMNrH7

**Comment by scossar** [comment]
Version 1.6.3 is in the WordPress repo now. It should fix the issue. Let me know if it doesn't.

**Comment by jasonbayton** [comment]
Confirmed fixed 😎
