### ISSUE TITLE
Adding staff colour - comment disappears

### ISSUE THREAD

**Issue by jasonbayton** [discourse/wp-discourse#311]
Just noticed when I went to highlight a comment, after adding staff colour it no longer synced to the website. Removing staff colour it immediately returned.

Have you seen this before?

**Comment by scossar** [comment]
Yes, the posts are returned from the Discourse `wordpress` route. That route filters posts in a few ways. One way it filters posts is that it only returns posts of the `regular` post type. When a staff color is added to a post the post type is changed to a `moderator_action` post type. This isn't something that the WordPress plugin has any control over.
