### ISSUE TITLE
Comments disappearing from posts

### ISSUE THREAD

**Issue by jasonbayton** [discourse/wp-discourse#323]
I've been using wp-discourse for a while, and just today noticed while checking out some older posts that on a bunch of them comments are no longer there.

Here's how it should be (no comments but ok) http://bit.ly/2QsW6hW
Here's how it is: http://bit.ly/2IFJHEk, http://bit.ly/2IBkr26

The corresponding discourse topics still exist and within post settings the link is still there. I've tried to force an update but haven't done an unlink/relink as that wouldn't tell me the root cause.

Have you seen this? Any idea what's happening?

Version: 1.7.6
WP version 4.9.8

**Comment by jasonbayton** [comment]
Looks like it has something to do with a recent server-move I did. I don't know why at the moment though.

**Comment by jasonbayton** [comment]
OK, so checking the logs maybe it's a PHP 7 issue, as in migrating I did move from 5.x
---
[Thu Oct 04 16:52:08.958744 2018] [php7:error] [pid 362] [client 177.1.81.226:11762] PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in /var/www/domain.org/wp-content/plugins/wp-discourse/lib/template-functions.php:80\nStack trace:\n#0 /var/www/domain.org/wp-content/plugins/wp-discourse/lib/discourse-comment-formatter.php(125): WPDiscourse\\DiscourseCommentFormatter\\DiscourseCommentFormatter->convert_relative_urls_to_absolute('https://discuss...', '<p>Hi Jason,Tha...')\n#1 /var/www/domain.org/wp-content/plugins/wp-discourse/lib/discourse-comment.php(299): WPDiscourse\\DiscourseCommentFormatter\\DiscourseCommentFormatter->format(4096)\n#2 /var/www/domain.org/wp-includes/class-wp-hook.php(286): WPDiscourse\\DiscourseComment\\DiscourseComment->comments_template('/var/www/bayton...')\n#3 /var/www/domain.org/wp-includes/plugin.php(203): WP_Hook->apply_filters('/var/www/bayton...', Array)\n#4 /var/www/domain.org/wp-includes/comment-template.php(1470): apply_filters('comments_templa...', '/var/www/bayton...')\n#5 /var/www/domain.org/wp-content/themes/themev4/parts/comments-widescreen.php(12): comments_template() in /var/www/domain.org/wp-content/plugins/wp-discourse/lib/template-functions.php on line 80, referer: https://www.google.com.br/
[Thu Oct 04 16:52:39.808188 2018] [php7:error] [pid 366] [client 76.67.58.250:56797] PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in /var/www/domain.org/wp-content/plugins/wp-discourse/lib/template-functions.php:80\nStack trace:\n#0 /var/www/domain.org/wp-content/plugins/wp-discourse/lib/discourse-comment-formatter.php(125): WPDiscourse\\DiscourseCommentFormatter\\DiscourseCommentFormatter->convert_relative_urls_to_absolute('https://discuss...', '<p>Thank you fo...')\n#1 /var/www/domain.org/wp-content/plugins/wp-discourse/lib/discourse-comment.php(299): WPDiscourse\\DiscourseCommentFormatter\\DiscourseCommentFormatter->format(4131)\n#2 /var/www/domain.org/wp-includes/class-wp-hook.php(286): WPDiscourse\\DiscourseComment\\DiscourseComment->comments_template('/var/www/bayton...')\n#3 /var/www/domain.org/wp-includes/plugin.php(203): WP_Hook->apply_filters('/var/www/bayton...', Array)\n#4 /var/www/domain.org/wp-includes/comment-template.php(1470): apply_filters('comments_templa...', '/var/www/bayton...')\n#5 /var/www/domain.org/wp-content/themes/themev4/parts/comments-widescreen.php(12): comments_template() in /var/www/domain.org/wp-content/plugins/wp-discourse/lib/template-functions.php on line 80, referer: https://www.google.ca/
[Thu Oct 04 16:52:42.120035 2018] [php7:error] [pid 495] [client 188.29.164.68:27520] PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in /var/www/domain.org/wp-content/plugins/wp-discourse/lib/template-functions.php:80\nStack trace:\n#0 /var/www/domain.org/wp-content/plugins/wp-discourse/lib/discourse-comment-formatter.php(125): WPDiscourse\\DiscourseCommentFormatter\\DiscourseCommentFormatter->convert_relative_urls_to_absolute('https://discuss...', '<p>Hey, I\\xE2\\x80\\x99ve ...')\n#1 /var/www/domain.org/wp-content/plugins/wp-discourse/lib/discourse-comment.php(299): WPDiscourse\\DiscourseCommentFormatter\\DiscourseCommentFormatter->format(6628)\n#2 /var/www/domain.org/wp-includes/class-wp-hook.php(286): WPDiscourse\\DiscourseComment\\DiscourseComment->comments_template('/var/www/bayton...')\n#3 /var/www/domain.org/wp-includes/plugin.php(203): WP_Hook->apply_filters('/var/www/bayton...', Array)\n#4 /var/www/domain.org/wp-includes/comment-template.php(1470): apply_filters('comments_templa...', '/var/www/bayton...')\n#5 /var/www/domain.org/wp-content/themes/themev4/parts/comments-widescreen.php(12): comments_t in /var/www/domain.org/wp-content/plugins/wp-discourse/lib/template-functions.php on line 80, referer: https://domain.org/
---

**Comment by scossar** [comment]
Thanks for reporting this! It looks like the DOM extension isn't installed on your new server. The plugin is trying to test for this, but it seems the test is wrong. Can you try installing it and restarting your server? https://stackoverflow.com/questions/14395239/class-domdocument-not-found

I'll fix the tests in the functions that are using DOMDocument.

**Comment by jasonbayton** [comment]
Thanks for the quick response!

I've added the missing package(s) and restarted Apache, just this one now: 

```
PHP Fatal error:  Uncaught Error: Call to undefined function WPDiscourse\\Shared\\mb_convert_encoding() 
```

**Comment by jasonbayton** [comment]
php-mbstring resolved that final error.

If it helps, some plugins detect missing packages and warn the plugin won't work, that might be worth looking in to :)

That it only affected the posts with comments makes sense now. Glad I was able to bring something to your attention even if my issue was only a simple one!
