### ISSUE TITLE
remove howtogeek.com, doc improve

### ISSUE THREAD

**Issue by pcegarra** [discourse/wp-discourse#326]
Seems they are using disqus

**Comment by coding-horror** [comment]
https://discuss.howtogeek.com/

still there

**Comment by erlend-sh** [comment]
Their Discourse forum is still operational, but the question here is are they still using Discourse for comments anywhere? It appears not:

https://discuss.howtogeek.com/t/htg-now-has-disqus-comments/73080/5

So we should indeed stop pointing to them as a wp-discourse demo.

**Comment by scossar** [comment]
Thanks! I've removed them from from the readme.
