### ISSUE TITLE
Trying to get property 'ID' of non-object

### ISSUE THREAD

**Issue by LeoColomb** [discourse/wp-discourse#330]
An error is regularly raised at the following line:

https://github.com/discourse/wp-discourse/blob/241a69269a911a71b58087c5ed509e4c9cb7bb8d/lib/sso-provider/discourse-sso.php#L46

> ErrorException: Trying to get property 'ID' of non-object
#.13 web/app/plugins/wp-discourse/lib/sso-provider/discourse-sso.php(46): sync_sso_record
#.12 web/wp/wp-includes/class-wp-hook.php(286): apply_filters
#.11 web/wp/wp-includes/class-wp-hook.php(310): do_action
#.10 web/wp/wp-includes/plugin.php(453): do_action
#.9 web/app/plugins/wp-discourse/lib/sso-client/client.php(264): auth_user
#.8 web/app/plugins/wp-discourse/lib/sso-client/client.php(137): parse_request
#.7 web/wp/wp-includes/class-wp-hook.php(286): apply_filters
#.6 web/wp/wp-includes/class-wp-hook.php(310): do_action
#.5 web/wp/wp-includes/plugin.php(453): do_action
#.4 web/wp/wp-settings.php(450): require_once
#.3 web/wp-config.php(9): require_once
#.2 web/wp/wp-load.php(42): require_once
#.1 admin.php(31): require_once
#.0 index.php(10): null

`$user` is a string containing the user email address.

---
Not really sure why, since [`wp_login` pass `\WP_User` object](https://codex.wordpress.org/Plugin_API/Action_Reference/wp_login).
https://github.com/discourse/wp-discourse/blob/3a7a5e1a629784c00b1f868bea5929f01d0b4b28/lib/sso-provider/discourse-sso.php#L35

**Comment by LeoColomb** [comment]
The error seems to come from:
https://github.com/discourse/wp-discourse/blob/241a69269a911a71b58087c5ed509e4c9cb7bb8d/lib/sso-client/client.php#L264

**Comment by scossar** [comment]
Sorry for the delay on this. There were two issues:

- the `sync_sso_record` method should return immediately if the SSO Provider option isn't enabled
- the `wp_login` action was being called with the wrong parameters in `client.php`

I'll push the fix to the master branch later today or early tomorrow.

**Comment by scossar** [comment]
This should be fixed as of version 1.8.3. I'm not sure how I missed that - the error was being logged on my dev site when the SSO Client option was enabled.

**Comment by LeoColomb** [comment]
@scossar Yes, fixed, thanks! 👍
