### ISSUE TITLE
when wordpress is sso provider, logout from discourse can not synchronize with wordpress 

### ISSUE THREAD

**Issue by seuliang** [discourse/wp-discourse#335]
when wordpress is sso provider, logout from discourse can not synchronize with wordpress, can not logout at wordpress

**Comment by seuliang** [comment]
when wordpress is sso provider, logging out from discourse can not synchronize with wordpress, can not log out at wordpress

**Comment by scossar** [comment]
You can do that by adding

```
https://example.com/?request=logout
```
to your Discourse site's 'logout redirect' setting. Replace `example.com` with your WordPress site domain.

**Comment by seuliang** [comment]
Thank you!
