### ISSUE TITLE
when wordpress is sso privider, can't visit discourse when users don't login.

### ISSUE THREAD

**Issue by seuliang** [discourse/wp-discourse#336]
when wordpress is sso privider, wp-discourse force users visit wordpress login page .

**Comment by scossar** [comment]
This should only be the case if you have enabled the 'login required' Site Setting on Discourse. If you want people to be able to see your forum without logging in, disable that setting.

You can also ask questions here: https://meta.discourse.org/c/support/wordpress

**Comment by seuliang** [comment]
I see. Thank you!
