### ISSUE TITLE
New posts not publishing because MySQL lock is never released

### ISSUE THREAD

**Issue by elivz** [discourse/wp-discourse#337]
We have been unable to publish new WordPress posts to Discourse for a few days, and I finally tracked it down to the database lock on line 131 of [`discourse-publish.php`](https://github.com/discourse/wp-discourse/blob/master/lib/discourse-publish.php#L131). It seems that `SELECT GET_LOCK( 'discourse_publish_lock', 0 ) got_it` always returns zero, so the sync code never runs. 

I don't have a lot of familiarity with MySQL's Locking functions, so I'm not sure how or why that lock got "stuck" and isn't being released. When I run the same query on the same database outside of PHP, it returns `1`, as one would hope. 

PHP 7.0.32
MySQL 5.7.24
WordPress 4.9.9
WP Discourse 1.8.7

**Comment by scossar** [comment]
Thanks for reporting that! I'll take a look at what could be going on and get back to you.

**Comment by scossar** [comment]
Have you made any recent changes to your site? Have you installed or reconfigured any persistent caching plugins, for example W3 Total Cache?

Do you have wp-cli installed on your site? If so, there may be a function call that can be used to release the lock. I'd still like to figure out where this has gone wrong, so any info you can give about changes to your site would be great.

**Comment by elivz** [comment]
No recent changes. We do use both Super Cache for static caching and [Redis Cache](https://wordpress.org/plugins/redis-cache/) for transient caching, but have done so since launch and haven't changed their configurations recently.

We are not currently running WP-CLI on the production server. I can look into installing it if need be.

**Comment by scossar** [comment]
Does the Redis Cache plugin give you an option to clear the cache? It seems like the correct value is in your database, but a cached value is being returned by `wp_cache_get`.

**Comment by scossar** [comment]
If this problem continues, there are a couple of possible ways the plugin could deal with it. I don't want to commit any changes to the publishing code on a Friday afternoon though. This is the first report I've heard about issues with the `discourse_publish_lock`. I'll look at this again early next week.

If you find any more details about what is going on, please let me know.

**Comment by elivz** [comment]
Sorry for the delay...just coming back to this project. It does appear to be related to the Redis persistent object cache. What would you think about adding a "group" parameter to the cache calls? I don't believe that would have any effect on the plugin's operation, & then I could siimply exclude those from persistent caching.

**Comment by scossar** [comment]
Thanks for getting back about this. I was wondering whether or not it was resolved. I'll look into adding a "group" parameter to the cache calls.

The database calls are cached here to deal with WordPress coding standards. I don't think that caching these calls is solving a real problem. I'll get a fix for you by Monday.

**Comment by scossar** [comment]
I think the best thing to do here is to just remove the cache from the database call. I've made that change in the beta branch, but haven't updated the master branch yet, or pushed the changes to the WordPress repo. I'll get that done tomorrow. 

If you'd like to try the changes, you can download the beta branch from here: https://github.com/discourse/wp-discourse/tree/beta

**Comment by scossar** [comment]
The cache from the database call has now been removed in the master branch. The fix is in version 1.8.8. It's available in the WordPress repo now. Let me know if this doesn't solve the problem for you.

**Comment by elivz** [comment]
Wonderful, thanks! I just upgraded and asked the content editors to let me know if they see any more problems with posting.
