### ISSUE TITLE
Do not want: users to verify email

### ISSUE THREAD

**Issue by fulldecent** [discourse/wp-discourse#339]
When a user accesses our Discourse for the first time when logging in with Wordpress SSO then they are presented with this page.

<img width="1344" alt="Screen Shot 2019-03-15 at 2 15 15 PM" src="https://user-images.githubusercontent.com/382183/54453213-3cc2a380-472d-11e9-9254-d0afc67c75fe.png">

Instead, my users are expecting a seamless experience. How may I disable this extra step?

Below are all the configuration settings we are using.

<img width="1097" alt="Screen Shot 2019-03-15 at 2 19 26 PM" src="https://user-images.githubusercontent.com/382183/54453436-b195dd80-472d-11e9-82b3-82765537daa2.png">
<img width="810" alt="Screen Shot 2019-03-15 at 2 19 30 PM" src="https://user-images.githubusercontent.com/382183/54453438-b195dd80-472d-11e9-8447-d5004782331e.png">
<img width="759" alt="Screen Shot 2019-03-15 at 2 19 33 PM" src="https://user-images.githubusercontent.com/382183/54453439-b22e7400-472d-11e9-8443-a4e3dac54028.png">
<img width="793" alt="Screen Shot 2019-03-15 at 2 19 36 PM" src="https://user-images.githubusercontent.com/382183/54453440-b22e7400-472d-11e9-8cbb-b51f46b4c9a7.png">
<img width="744" alt="Screen Shot 2019-03-15 at 2 19 39 PM" src="https://user-images.githubusercontent.com/382183/54453441-b22e7400-472d-11e9-9cca-95ce4c362e4b.png">
<img width="656" alt="Screen Shot 2019-03-15 at 2 19 42 PM" src="https://user-images.githubusercontent.com/382183/54453443-b22e7400-472d-11e9-8157-927b406522e3.png">

**Comment by scossar** [comment]
The reason your users are having to respond to the confirmation email before being able to access Discourse is that your site is not using the default WordPress registration system. This means there is no way for the WP Discourse plugin to know if the user's email addresses have been verified or not. 

If you know that your user's email addresses are being verified by your registration system, there is a filter that you can use prevent the confirmation email being sent. You can find details about how to use it here: https://meta.discourse.org/t/how-to-turn-off-discourse-email-verification/75365/4.

If you have questions about this, feel free to ask on our forum: https://meta.discourse.org/c/support/wordpress

**Comment by fulldecent** [comment]
Excellent, thank you. I am using the filter and it is no longer sending the extra confirmation.
