### ISSUE TITLE
You are not connected to Discourse. 

### ISSUE THREAD

**Issue by svrcore** [discourse/wp-discourse#340]
I got this information after my configuration completed. 

> "You are not connected to Discourse. If you are setting up the plugin, this notice should go away after completing the form on this page."

I checked everything and didn't find the solution, I can accessed the rest url via Curl command in the host server, both Wordpress and Discourse.

Any configuration is normal in my Wordpress except I changed the plugin path via wp-config.php like this:

> if ( !defined('ABSPATH') )
        define('ABSPATH', dirname(__FILE__) . '/');
>define ('WP_CONTENT_FOLDERNAME', 'func');

>define ('WP_CONTENT_DIR', ABSPATH . WP_CONTENT_FOLDERNAME);

>define('WP_SITEURL', 'https://' . $_SERVER['HTTP_HOST'] . '/');
>define('WP_CONTENT_URL', WP_SITEURL . WP_CONTENT_FOLDERNAME);

I am not sure if this configuration caused the issue.

**Comment by scossar** [comment]
This has been resolved: https://meta.discourse.org/t/everything-is-fine-but-you-are-not-connected-to-discourse/114976.
