### ISSUE TITLE
SSO Client Bug: Email Aliases are incorrectly handled by the plugin.

### ISSUE THREAD

**Issue by amanning11** [discourse/wp-discourse#346]
Email aliases are valid in both WP and in Discourse.
When using WP-Discourse as an SSO Provider, a user with an alias in their email address will be unable to login.

File: lib > sso-client > client.php
Line: 393
$response = array_map( 'urldecode', $response );

**Should be:**
$response = array_map( 'rawurldecode', $response );

**Reason:**

$email = array('my+email@gmail.com');
$**user_will_not_be_able_to_login** = array_map( 'urldecode', $email ); // 'my email@gmail.com'
$**correct** = array_map( 'rawurldecode', $email ); // 'my+email@gmail.com'

Notes:
Wordpress: 5.2.3
WP-Discourse: 1.9.3

**Comment by scossar** [comment]
Thanks for reporting this! I'll fix it.

**Comment by scossar** [comment]
This has been fixed in WP Discourse version 1.9.4. 

Thanks for reporting it!

**Comment by amanning11** [comment]
I've had a look at the release and I think I may have made a typo in the issue that has lead you astray.

Discourse is the sso provider. Wordpress is the sso client, this is why I mentioned the client file in my issue. Also I'm not using php 5.4.

Making the suggested fix resolves the issue for my install. I will test 1.9.4 tomorrow but I have doubts it will resolve this issue.

**Comment by scossar** [comment]
Isn't this the change you were looking for: https://github.com/discourse/wp-discourse/blob/master/lib/sso-client/client.php#L393? It works for me.

The commits to do with php 5.4 were for another change. I'd really like to stop supporting php 5.4, it makes it hard to write nice code.

**Comment by amanning11** [comment]
Awesome. Only saw a reference to the php 5.4 in the release. Didn't go digging in the commits.

I'll test it tomorrow but I bet its all good. Thanks
