### ISSUE TITLE
Possible bug: SSO Client, updating both username and email at the same time

### ISSUE THREAD

**Issue by aaron-manning** [discourse/wp-discourse#350]
Hi,

When using discourse as an SSO Provider, users are able to update both their username and their email (this appears to be the default behaviour of Discourse).

Please look at WP Discourse file: client.php ~line 157

Here we can see the code:
		
```
// If the logged in user's credentials don't match the credentials returned from Discourse, return an error.
		$wp_user = get_user_by( 'ID', $user_id );
		if ( $wp_user->user_login !== $username && $wp_user->user_email !== $email ) {

			return new \WP_Error( 'mismatched_users' );
		}
```

This will cause a mismatch error whenever a discourse user changes both their username and email at the same time (or at different times but do not log in to WP via SSO in-between these updates).

I've done some digging through the code and i'm not sure why this check needs to exist.
WP users already have an external ID field created in their account via WP Discourse that uniquely identifies their associated Discourse account.

SSO requests to Discourse use a secret and a nonce, isn't this sufficient protection to not need this check?

Thanks

**Comment by scossar** [comment]
Thanks! It sounds like you are correct. I'll take a look at it when I get
back to work on Monday.

**Comment by scossar** [comment]
Sorry for the delay on this. That check exists for a reason, but is not the ideal solution. I'll try to get it fixed this week.

**Comment by amanning11** [comment]
Would you mind explaining why it's needed? Thanks

**Comment by scossar** [comment]
When an existing WordPress account is synced with an existing Discourse
account, it handles the edge case of the wrong user being logged in on
Discourse. There will be a fix for this issue in the next update. It will
be available within the next couple of days.
