### ISSUE TITLE
Wiki missing

### ISSUE THREAD

**Issue by Polarisation** [discourse/wp-discourse#351]
`README.md` has multiple links to a wiki for this repository: [https://github.com/discourse/wp-discourse/wiki](https://github.com/discourse/wp-discourse/wiki).

The link simply redirects to the repository root for me. Presumably this means it either no longer exists, or is not public.

Can the documentation links be fixed or updated?

**Comment by phallguy** [comment]
Where can we find the instructions that were previously available in the Wiki?

**Comment by scossar** [comment]
Read through https://meta.discourse.org/t/wp-discourse-plugin-installation-and-setup/50752. If you still have questions, do a quick search in our WordPress category: https://meta.discourse.org/c/support/wordpress. If you still have questions, create a topic in the WordPress category and it will get answered.

**Comment by phallguy** [comment]
Thanks for the heads up...didn't see any link to the meta discussion in the readmes.

**Comment by scossar** [comment]
I'll fix that.
