### ISSUE TITLE
Wordpress Deleted Users from Discourse

### ISSUE THREAD

**Issue by mcanno** [discourse/wp-discourse#354]
Hello, 

I have been managing wordpress with discourse with the plugin WP-DISCOURSE. 

We have Wordpress as a main site(users registration) and discourse synchronize with the wp-discourse plugin. 

We are experiencing that  some wordpress users are being deleted from discourse.  I have change the parameter on discourse settings to delete users after 14 days from accounts without email verification (now this value has been set to 0). But from time to time we see, again, that several wordpress users accounts being deleted form discourse. 

Is there any other cause, that can produce wordpress users accounts being deleted from discourse?
How we can avoid such discourse behaviour?

Regards, Manuel

**Comment by scossar** [comment]
If you are still running into problems with this, can you ask your question here: https://meta.discourse.org/c/support/6?
