### ISSUE TITLE
Change how WordPress is written on discourse.org/integrations

### ISSUE THREAD

**Issue by simison** [discourse/wp-discourse#365]
Hi! Super tiny nitpick — could `Wordpress` be changed to correct format `WordPress` (with capital P) at https://www.discourse.org/integrations

<img width="925" alt="Screenshot 2020-06-20 at 19 57 52" src="https://user-images.githubusercontent.com/87168/85207316-9c482f80-b330-11ea-854e-3fe4831c1c00.png">

Thank you! Lemme know if there's better place to report this.

**Comment by coding-horror** [comment]
Sure! Seems like a good idea to me, and a simple change.. thanks for pointing this out! 🤗
