### ISSUE TITLE
Cannot connect to discourse

### ISSUE THREAD

**Issue by psjamesp** [discourse/wp-discourse#392]
![image](https://user-images.githubusercontent.com/38379414/111356237-8d43a300-865e-11eb-8179-96001cd94309.png)

I have tried multiple API keys and none of them work. 

![image](https://user-images.githubusercontent.com/38379414/111356406-b5cb9d00-865e-11eb-809c-a3da5d9cd034.png)

**Comment by psjamesp** [comment]
Still can't connect.

**Comment by maiki** [comment]
Hi @psjamesp. :wave: 

If this is still an issue, please report it at https://meta.discourse.org. We'll check it out, you can mention me (@maiki). ^_^
