### ISSUE TITLE
Pictures missing on imported posts

### ISSUE THREAD

**Issue by sociocracyforall** [discourse/wp-discourse#420]
For some reason the pictures work when the post is initially imported, but then something changes and the files seem to be missing and do not display.

This can be seen here:
https://forums.sociocracyforall.org/t/there-is-no-hierarchy-in-sociocracy-right/1095

If I revert to the original edit of the post, the pictures will display, and then it will change again and the picture won't show up.

**Comment by hhslepicka** [comment]
@sociocracyforall did you manage to overcome this issue? Looking at your link the images are being displayed correctly.

**Comment by maiki** [comment]
Hi @sociocracyforall. :wave: 

If this continues to happen in the latest version, please let us know at https://meta.discourse.org (you can mention me, @maiki), and we'll take a look. ^_^
