### ISSUE TITLE
Error for on unrelated posts since 2.3.5

### ISSUE THREAD

**Issue by rdrouche** [discourse/wp-discourse#435]
Hello,

Since update 2.3.5, an error is displayed on posts that are not linked to a topic on Discourse.

Below is a capture to the error.

https://1drv.ms/u/s!Aiq0yirkk82kj70y3doSCKLWp6BZtQ?e=oK9YCe

The return to version 2.3.4 corrects the problem.

Yesterday I tested with version 2.3.7 and the problem is still present.

Romain

**Comment by maiki** [comment]
Hi @rdrouche. :wave: 

Sorry that was happening. If it continues to happen with the latest version, please let us know at https://meta.discourse.org, and we'll take a look. You can mention me there (@maiki). ^_^
