### ISSUE TITLE
Only Two Replies Displayed

### ISSUE THREAD

**Issue by cogdog** [discourse/wp-discourse#462]
My WordPress settings have `Max Visible Comments` set to 8 but are only displaying 2. How do I get more?

See bottom of post here https://podcast.oeglobal.org/2022/09/30/voices-41/

**Comment by maiki** [comment]
It currently shows the comments in sync. Perhaps there was a syncing issue before. ^_^

**Comment by cogdog** [comment]
No errors logged. I'm not sure what this means, but republishing to discourse brought in all the replies.
