### ISSUE TITLE
Shortcodes for Discourse

### ISSUE THREAD

**Issue by tomspilman** [discourse/wp-discourse#51]
It would be nice to have some shortcodes for easy linking Discourse content from WordPress posts.

```
[discourse user=TomSpilman]
[discourse category=General]
[discourse group=moderators]
```

... or something like that.

It could even get fancy later allowing embedding of discussions, member profiles, etc.

**Comment by scossar** [comment]
There's a wp-discourse-shortcodes plugin here: it's a work-in-progress. I'll be looking at it again next week.
