### ISSUE TITLE
Warning displayed and no new topic created when post automatically created via scheduling

### ISSUE THREAD

**Issue by evilzug** [discourse/wp-discourse#79]
When using the automatic post scheduling system in WordPress, if I do so with the 'publish to discourse' box checked off, it doesn't seem to work.

I get the following error at the bottom of my post, right above the 'start the discussion' link:
**Warning: file_get_contents(/wordpress.json?best=5&min_trust_level=1&min_score=30&min_replies=5&bypass_trust_level_score=50) [function.file-get-contents]: failed to open stream: No such file or directory in /home/wp_f3th5b/tommannino.com/wp-content/plugins/wp-discourse-master/wp-discourse.php on line 191**

The 'Start the discussion' link is also just a link back to the actual post on my WordPress.

Note that if I do the following, it seems to fix it:
- edit the post,
- untick 'publish to discourse,' 
- click update
- let page reload
- tick 'publish to discourse'
- click update
- let page reload
  ...the thread gets created and everything works fine.

Also perhaps worth noting that my WordPress install and discourse install are on two separate hosting services.

Also may or may not be related to this issue here:
https://github.com/discourse/wp-discourse/issues/69

**Comment by bartv42** [comment]
What's the status of supporting scheduled posts?

**Comment by scossar** [comment]
This has been fixed.
