### ISSUE TITLE
Does not work with nginx / latest wordpress

### ISSUE THREAD

**Issue by servermeta** [discourse/wp-discourse#83]
Hello Guys,

I'm running wordpress 4.0 on latest ubuntu from this docker container:

https://github.com/eugeneware/docker-wordpress-nginx

wordpress is also running behind another nginx reverse proxy, but on wordpress everything seems to work fine.

I'm trying to use wp-discourse to connect it with a working discourse instance.

Anyhow it doesnt work, and it breaks in 2 ways:

1) Comments are not shown in the posts, also the link is broken:

http://it.servermeta.net/ciao-mi-chiamo-gio-ho-7-figli-una-pentola/

2) Forum posts are not created.

The only meaningful error I found was:

```
2014/09/17 22:57:42 [error] 428#0: *1038 FastCGI sent in stderr: "PHP message: PHP Warning:  First parameter must either be an object or the name of an existing class in /usr/share/nginx/www/wp-content/plugins/wp-discourse-master/wp-discourse.php on line 410

PHP message: PHP Warning:  file_get_contents(/wordpress.json?best=5&amp;min_trust_level=1&amp;min_score=30&amp;min_replies=5&amp;bypass_trust_level_score=50): failed to open stream: No such file or directory in /usr/share/nginx/www/wp-content/plugins/wp-discourse-master/wp-discourse.php on line 195" while reading upstream, client: 172.17.42.1, server: localhost, request: "GET /ciao-mi-chiamo-gio-ho-7-figli-una-pentola/ HTTP/1.0", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "it.servermeta.net"
```

Any suggestion?

EDIT: I found this but is not related to Ubuntu. It seems like it doesnt help. I'm trying several fixes.

http://www.nginxtips.com/php-fpm-connect-to-unixtmpphp5-fpm-sock-failed-2-no-such-file-or-directory/

**Comment by retlehs** [comment]
in the code there's a note that says `// todo may have $json->errors with list of errors` — this should probably be built out :warning:

**Comment by retlehs** [comment]
closing in favor of #85
