### ISSUE TITLE
Category isn't being set

### ISSUE THREAD

**Issue by mrrcollins** [discourse/wp-discourse#92]
In WP settings I have the **Published category** category set. New topics for blog posts are created in Discourse, but the category is blank.

WP 4.1, WP-Discourse 0.6.1

**Comment by Squawkers13** [comment]
This happened to me too.

**Comment by eha1** [comment]
same here.

**Comment by techAPJ** [comment]
I just pushed a fix for this, please reply here if the problem persists.

**Comment by eha1** [comment]
hi, thanks for the update, but i receive a "fatal error" when activating the 0.6.2. version of the plugin.
br, eric

**Comment by henrynet** [comment]
v0.6.2
Fatal error: Access to undeclared static property: Discourse::$version in /var/www/html/wp-content/plugins/wp-discourse-master/wp-discourse.php on line 100

It seems be another issue.

**Comment by henrynet** [comment]
049a184be2d889252042f60d8ce2320ba2463374
removed the line "static $version ='0.0.1';"

try to add it back then the plugin can be activated successfully

**Comment by techAPJ** [comment]
Thanks for the catch @henrynet! Just pushed a fix: https://github.com/discourse/wp-discourse/commit/1bb9d4823683ddf56f23906c71267b5da659f522

cc @retlehs: I think we should remove the property `version` and the reference where it's called. What do you think?

**Comment by eha1** [comment]
@techAPJ  just tested your latest version, activation works but rest of the plugin doesn´t work now (on my demo site), no publishing of posts to discourse installation, no hiding of existing comments section, no checkbox when adding a new article on wp

**Comment by techAPJ** [comment]
@retlehs can you please verify if the latest version is working fine on a fresh WP install?

**Comment by retlehs** [comment]
looking now, will submit a PR soon

broke when #97 was merged, forgot to update one of the function references after separating things out

**Comment by mrrcollins** [comment]
And to add to this, I was looking at the code and it looked like the plugin looks at the categories in Wordpress. I created a new category in Wordpress with the same name as the category I want it to go into in Discourse and it works.
