### ISSUE TITLE
tags / releases

### ISSUE THREAD

**Issue by retlehs** [discourse/wp-discourse#96]
this repo is missing tags/a release. every time a new version is pushed, a new tag should be created. nowadays it's pretty easy with github:

https://github.com/discourse/wp-discourse/releases/new

**Comment by retlehs** [comment]
an official `CHANGELOG.md` would be cool, too

**Comment by retlehs** [comment]
@techAPJ fyi, composer support won't work until a release is tagged

**Comment by retlehs** [comment]
added a changelog and tagged 0.6.3

https://github.com/discourse/wp-discourse/releases/tag/0.6.3

**Comment by techAPJ** [comment]
:+1:
